const EXPERIENCE_LEVELS=Object.freeze(["beginner","intermediate","advanced"]);
const SKILLS=Object.freeze(["React","JavaScript","TypeScript","HTML","CSS","Responsive Design","Accessibility","State Management","Node.js","Express","MongoDB","SQL","REST APIs","Authentication","File Upload","WebSockets","Unit Testing","Integration Testing","Frontend Testing","API Testing","End-to-End Testing","Git Workflow","Branching","Debugging","CI/CD","Documentation","Code Review","Security Basics"]);
const TASK_TYPES=Object.freeze(["UI improvement","Bug fixing","Documentation","Testing","Accessibility","Backend API","Database","Security","Performance","Refactoring"]);
const AVAILABLE_TIMES=Object.freeze(["under_30_minutes","30_to_60_minutes","1_to_2_hours","2_to_4_hours","more_than_4_hours"]);
const TIME_MINUTES=Object.freeze({under_30_minutes:30,"30_to_60_minutes":60,"1_to_2_hours":120,"2_to_4_hours":240,more_than_4_hours:480});
const SKILL_ALIASES=Object.freeze({js:"JavaScript",javascript:"JavaScript",ts:"TypeScript",node:"Node.js",nodejs:"Node.js","node.js":"Node.js",mongo:"MongoDB",mongodb:"MongoDB","responsive css":"Responsive Design","rest api":"REST APIs",rest:"REST APIs",websocket:"WebSockets",websockets:"WebSockets",css:"CSS",react:"React",express:"Express"});
const RELATED_TASKS=Object.freeze({"UI improvement":["Accessibility","Refactoring"],Accessibility:["UI improvement"],"Bug fixing":["Debugging","Testing"],Testing:["Bug fixing"],"Backend API":["Database","Security"],Database:["Backend API"],Security:["Backend API"],Performance:["Refactoring"],Refactoring:["Performance","Bug fixing"]});
const COMPLETION_CHECK_TYPES=Object.freeze(["branch_exists","file_modified","file_not_modified","path_pattern_modified","minimum_changed_files","maximum_changed_files","commit_exists","pull_request_exists","workflow_passed","test_result_available","css_media_query_present","text_pattern_present","user_confirmation","maintainer_confirmation","no_protected_file_modified","no_backend_file_modified","no_frontend_file_modified"]);
const ACTIVE_SESSION_STATUSES=Object.freeze(["recommended","selected","branch_created","in_progress","ready_for_commit","committed","pull_request_created","blocked"]);
const SCORE_WEIGHTS=Object.freeze({requiredSkills:35,experience:20,time:15,taskType:10,clarity:10,eligibility:5,beginnerFriendly:5});
const normalizeToken=value=>String(value||"").trim().replace(/\s+/g," ");
function normalizeSkill(value){const raw=normalizeToken(value),alias=SKILL_ALIASES[raw.toLowerCase()],canonical=SKILLS.find(skill=>skill.toLowerCase()===raw.toLowerCase());return alias||canonical||null;}
function normalizeTaskType(value){const raw=normalizeToken(value);return TASK_TYPES.find(type=>type.toLowerCase()===raw.toLowerCase())||null;}
module.exports={EXPERIENCE_LEVELS,SKILLS,TASK_TYPES,AVAILABLE_TIMES,TIME_MINUTES,SKILL_ALIASES,RELATED_TASKS,COMPLETION_CHECK_TYPES,ACTIVE_SESSION_STATUSES,SCORE_WEIGHTS,normalizeToken,normalizeSkill,normalizeTaskType};
