const { HEALTH_SCORE_VERSION, HEALTH_WEIGHTS, HEALTH_LEVELS, HEALTH_RANGES } = require("./repositoryHealth");
module.exports = { HEALTH_SCORE_VERSION, HEALTH_SCORE_WEIGHTS: HEALTH_WEIGHTS, HEALTH_SCORE_LEVELS: HEALTH_LEVELS, SUPPORTED_HEALTH_RANGES: HEALTH_RANGES };
