const test=require("node:test"),assert=require("node:assert/strict");
const permission=require("../services/callPermissionService"),service=require("../services/callService");
const{REPOSITORY_PERMISSIONS:P,ROLE_PERMISSION_MAP}=require("../constants/repositoryPermissions");

const host="507f1f77bcf86cd799439011",invitee="507f1f77bcf86cd799439012",repo="507f1f77bcf86cd799439013",callId="507f1f77bcf86cd799439014";
const call=()=>({_id:callId,callType:"repository",repository:repo,status:"active",acceptingParticipants:true,maxParticipants:4,initiatedBy:host});
const access=(role,status="active")=>({role,status,permissions:ROLE_PERMISSION_MAP[role]||[]});
const participant=(user,status="joined",role="participant")=>({_id:`row-${user}`,call:callId,user,status,role,save:async function(){return this;}});
function deps({role="reviewer",status="active",rows=[participant(host,"joined","host")],users={[invitee]:{_id:invitee,username:"reviewer-user"}},max=4}={}){const value=call();value.maxParticipants=max;return{CallModel:{findById:async()=>value},ParticipantModel:{findOne:async filter=>rows.find(row=>String(row.user)===String(filter.user))||null,countDocuments:async()=>rows.filter(row=>["invited","ringing","joined"].includes(row.status)).length,create:async input=>{const row=participant(input.user,input.status);row.invitedBy=input.invitedBy;rows.push(row);return row;}},UserModel:{findById:async id=>users[id]||null,findOne:async query=>Object.values(users).find(user=>user.username===query.username)||null},resolveRepositoryPermissionContext:async(_repository,userId)=>String(userId)===invitee?access(role,status):access("owner"),createNotification:async()=>({})};}

test("all active repository-view roles, including Reviewer, may be invited",async()=>{for(const role of["reviewer","viewer","tester","deployment_manager","temporary_contributor"]){const result=await permission.activeRepositoryInvitee(repo,invitee,deps({role}));assert.equal(result.role,role);assert.ok(result.permissions.includes(P.REPOSITORY_VIEW));}});
test("expired Temporary Contributors receive the stable expiry error",async()=>{await assert.rejects(()=>permission.activeRepositoryInvitee(repo,invitee,deps({role:"temporary_contributor",status:"expired"})),error=>error.code==="CALL_MEMBER_ACCESS_EXPIRED");});
test("removed, suspended, and unrelated users are inactive",async()=>{for(const context of[{role:null,status:null},{role:"reviewer",status:"suspended"}])await assert.rejects(()=>permission.activeRepositoryInvitee(repo,invitee,{resolveRepositoryPermissionContext:async()=>({...context,permissions:context.role?ROLE_PERMISSION_MAP[context.role]:[]})}),error=>error.code==="CALL_MEMBER_INACTIVE");});
test("owner access and populated identifiers normalize correctly",async()=>{const owner={_id:invitee};const result=await permission.activeRepositoryInvitee({_id:repo},owner,{resolveRepositoryPermissionContext:async(repositoryId,userId)=>{assert.equal(permission.id(repositoryId),repo);assert.equal(userId,invitee);return access("owner");}});assert.equal(result.role,"owner");});
test("username resolves to the internal user ID and active Reviewer is invited",async()=>{const local=deps(),row=await service.inviteParticipant(callId,host,"reviewer-user",local);assert.equal(String(row.user),invitee);assert.equal(row.status,"invited");});
test("arbitrary usernames cannot bypass user or repository authorization",async()=>{await assert.rejects(()=>service.resolveCallInvitee("not-a-member",deps()),error=>error.code==="CALL_MEMBER_NOT_FOUND");const local=deps({role:null,status:null});await assert.rejects(()=>service.inviteParticipant(callId,host,invitee,local),error=>error.code==="CALL_MEMBER_INACTIVE");});
test("existing participants and invitations cannot be duplicated",async()=>{for(const status of["joined","invited"]){const rows=[participant(host,"joined","host"),participant(invitee,status)],local=deps({rows});await assert.rejects(()=>service.inviteParticipant(callId,host,invitee,local),error=>error.code===(status==="joined"?"CALL_ALREADY_PARTICIPANT":"CALL_INVITATION_ALREADY_PENDING"));}});
test("the four-participant limit is enforced",async()=>{const rows=[participant(host,"joined","host"),participant("u2"),participant("u3"),participant("u4")],local=deps({rows});await assert.rejects(()=>service.inviteParticipant(callId,host,invitee,local),error=>error.code==="CALL_PARTICIPANT_LIMIT");});
test("only a joined host may invite",async()=>{for(const row of[participant(host,"joined","participant"),participant(host,"left","host")]){const local=deps({rows:[row]});await assert.rejects(()=>service.inviteParticipant(callId,host,invitee,local),error=>error.code==="CALL_FORBIDDEN");}});
test("repository role permission mappings remain unchanged and view-capable",()=>{for(const role of["owner","maintainer","viewer","issue_manager","tester","reviewer","temporary_contributor","deployment_manager"])assert.ok(ROLE_PERMISSION_MAP[role].includes(P.REPOSITORY_VIEW));});
