const assert = require("node:assert/strict");
const test = require("node:test");
const mongoose = require("mongoose");
const Repository = require("../models/repoModel");
const Issue = require("../models/issueModel");
const Session = require("../models/contributionSessionModel");
const { validateProfile } = require("../services/contributionProfileService");
const { validateGuide, safePath } = require("../services/contributionGuideService");
const { scoreRecommendation } = require("../services/contributionRecommendationService");
const { analyzeRelevantFiles } = require("../services/contributionFileAnalysisService");
const { calculateProgress } = require("../services/contributionProgressService");
const { buildSkillReport } = require("../services/contributionReportService");
const { proposedBranch } = require("../controllers/contributionController");
const { SCORE_WEIGHTS } = require("../constants/contributionConstants");

const id = () => new mongoose.Types.ObjectId();
const profile = (overrides = {}) => ({ experienceLevel: "beginner", skills: ["React", "CSS", "Git Workflow"], preferredTaskTypes: ["UI improvement"], availableTime: "1_to_2_hours", learningGoals: ["Accessibility"], visibility: "private", ...overrides });
const guide = (overrides = {}) => ({ enabled: true, difficulty: "beginner", estimatedMinutes: 60, requiredSkills: ["React", "CSS"], optionalSkills: ["Accessibility"], taskType: "UI improvement", projectArea: "settings", beginnerFriendly: true, relevantFiles: [{ path: "src/Settings.jsx", reason: "Settings UI", relevance: "required" }], completionChecks: [{ key: "branch", label: "Branch exists", checkType: "branch_exists", configuration: {}, required: true }], ...overrides });
const issue = overrides => ({ _id: id(), number: 7, title: "Improve settings layout", body: "Make settings responsive", labels: [{ name: "good first issue" }], contributionGuide: guide(), ...overrides });

test("valid skill profile is normalized", () => assert.deepEqual(validateProfile(profile()).skills, ["React", "CSS", "Git Workflow"]));
test("invalid experience is rejected", () => assert.throws(() => validateProfile(profile({ experienceLevel: "expert" })), /valid experience/));
test("invalid skill is rejected", () => assert.throws(() => validateProfile(profile({ skills: ["Telepathy"] })), /Unsupported/));
test("skill aliases normalize deterministically", () => assert.deepEqual(validateProfile(profile({ skills: ["js", "nodejs"] })).skills, ["JavaScript", "Node.js"]));
test("duplicate profile skills collapse", () => assert.deepEqual(validateProfile(profile({ skills: ["css", "CSS"] })).skills, ["CSS"]));
test("profile requires a skill", () => assert.throws(() => validateProfile(profile({ skills: [] })), /at least one/));
test("valid guide is normalized", () => assert.equal(validateGuide(guide(), id()).taskType, "UI improvement"));
test("invalid guide estimate is rejected", () => assert.throws(() => validateGuide(guide({ estimatedMinutes: 2 }), id()), /invalid/));
test("unsupported completion check is rejected", () => assert.throws(() => validateGuide(guide({ completionChecks: [{ key: "x", label: "x", checkType: "run_shell" }] }), id()), /supported/));
test("duplicate completion keys are rejected", () => assert.throws(() => validateGuide(guide({ completionChecks: [{ key: "x", label: "x", checkType: "branch_exists" }, { key: "x", label: "x", checkType: "commit_exists" }] }), id()), /unique/));
test("protected contribution paths are rejected", () => assert.throws(() => safePath(".env"), /Protected/));
test("parent traversal paths are rejected", () => assert.throws(() => safePath("../secret"), /Invalid/));
test("score remains within 0 and 100", () => { const value = scoreRecommendation(profile(), issue(), { eligible: true }).suitabilityScore; assert.ok(value >= 0 && value <= 100); });
test("score category points do not exceed maxima", () => { const value = scoreRecommendation(profile(), issue(), { eligible: true }); for (const [key, max] of Object.entries(SCORE_WEIGHTS)) assert.ok(value.breakdown[key] <= max); });
test("full skill match earns all skill points", () => assert.equal(scoreRecommendation(profile(), issue()).breakdown.requiredSkills, 35));
test("partial skill match earns proportional skill points", () => assert.equal(scoreRecommendation(profile({ skills: ["React"] }), issue()).breakdown.requiredSkills, 18));
test("experience match earns full experience points", () => assert.equal(scoreRecommendation(profile(), issue()).breakdown.experience, 20));
test("time fit earns full time points", () => assert.equal(scoreRecommendation(profile(), issue()).breakdown.time, 15));
test("preferred task earns full task points", () => assert.equal(scoreRecommendation(profile(), issue()).breakdown.taskType, 10));
test("beginner friendly earns label points", () => assert.equal(scoreRecommendation(profile(), issue()).breakdown.beginnerFriendly, 5));
test("eligibility controls actionable result", () => { assert.equal(scoreRecommendation(profile(), issue(), { eligible: false }).actionable, false); assert.equal(scoreRecommendation(profile(), issue(), { eligible: true }).actionable, true); });
test("recommendation reasons cite matched evidence", () => assert.match(scoreRecommendation(profile(), issue(), { eligible: true }).reasons.join(" "), /Matches React, CSS/));
test("maintainer file hints are returned first", () => { const repo = { content: [{ path: "src/Settings.jsx" }] }; assert.equal(analyzeRelevantFiles(repo, issue())[0].source, "maintainer"); });
test("file analysis excludes protected content", () => { const repo = { content: [{ path: ".env" }, { path: "src/Settings.jsx" }] }; assert.equal(analyzeRelevantFiles(repo, issue()).some(value => value.path === ".env"), false); });
test("progress requires real evidence", () => { const result = calculateProgress({}, { checks: [], changedFiles: [], branchExists: false, testingEvidence: false, commitId: null, pullRequest: null }, []); assert.equal(result.percent, 5); });
test("branch evidence advances progress", () => { const result = calculateProgress({}, { checks: [], changedFiles: [], branchExists: true, testingEvidence: false, commitId: null, pullRequest: null }, []); assert.equal(result.items.find(value => value.key === "branch_created").status, "completed"); });
test("diff evidence advances file progress", () => { const result = calculateProgress({}, { checks: [], changedFiles: [{ path: "src/a.js" }], branchExists: true, testingEvidence: false, commitId: null, pullRequest: null }, []); assert.equal(result.items.find(value => value.key === "expected_files").status, "completed"); });
test("commit evidence advances commit progress", () => { const result = calculateProgress({}, { checks: [], changedFiles: [], branchExists: true, testingEvidence: false, commitId: "abc", pullRequest: null }, []); assert.equal(result.items.find(value => value.key === "commit_created").status, "completed"); });
test("pull request evidence advances PR progress", () => { const result = calculateProgress({}, { checks: [], changedFiles: [], branchExists: true, testingEvidence: false, commitId: "abc", pullRequest: id() }, []); assert.equal(result.items.find(value => value.key === "pull_request_created").status, "completed"); });
test("personal branch follows mentor naming format", () => { const value = proposedBranch({ username: "Ada Lovelace" }, { number: 7, title: "Improve mobile navbar" }, { _id: id() }); assert.equal(value, "mentor/ada-lovelace/issue-7-improve-mobile-navbar"); });
test("report never awards selected skills without evidence", () => { const report = buildSkillReport({ contributor: id(), skillProfileSnapshot: profile() }, { _id: id(), name: "repo" }, issue(), { changedFiles: [], checks: [], workflowPassed: false, testingEvidence: false, commitId: null, pullRequest: null }); assert.deepEqual(report.skillsDemonstrated, []); assert.ok(report.skillsToImprove.includes("React")); });
test("testing points require stored evidence", () => { const base = { changedFiles: [], checks: [], workflowPassed: false, testingEvidence: false, commitId: null, pullRequest: null }; assert.equal(buildSkillReport({ contributor: id(), skillProfileSnapshot: profile() }, { _id: id(), name: "repo" }, issue(), base).breakdown.testing, 0); });
test("commit and PR points require evidence", () => { const report = buildSkillReport({ contributor: id(), skillProfileSnapshot: profile() }, { _id: id(), name: "repo" }, issue(), { changedFiles: [], checks: [], workflowPassed: false, testingEvidence: false, commitId: null, pullRequest: null }); assert.equal(report.breakdown.commitQuality, 0); assert.equal(report.breakdown.pullRequestQuality, 0); });
test("final report score remains bounded", () => { const report = buildSkillReport({ contributor: id(), skillProfileSnapshot: profile() }, { _id: id(), name: "repo" }, issue(), { changedFiles: [{ path: "src/App.jsx" }, { path: "src/app.css" }], checks: [{ required: true, status: "passed" }], workflowPassed: true, testingEvidence: true, commitId: "abc", pullRequest: id() }); assert.ok(report.score >= 0 && report.score <= 100); });
test("issue model accepts contribution guide", () => { const document = new Issue({ repository: id(), number: 1, title: "Guided", contributionGuide: guide() }); assert.equal(document.validateSync(), undefined); });
test("session model accepts evidence snapshots", () => { const document = new Session({ repository: id(), issue: id(), contributor: id(), skillProfileSnapshot: profile(), recommendationSnapshot: { suitabilityScore: 88 } }); assert.equal(document.validateSync(), undefined); });
test("repository model remains compatible with guided branch", () => { const document = new Repository({ name: `guided-${id()}`, owner: id(), branches: [{ name: "contribute/ada/issue-7-abcde", head: null }] }); assert.equal(document.validateSync(), undefined); });
