const test=require("node:test"),assert=require("node:assert/strict");
const service=require("../services/callService");
const Conversation=require("../models/conversationModel"),chat=require("../services/chatService");

const now=new Date("2026-07-18T12:00:00.000Z");
const makeCall=(status,ageMs=0,extra={})=>({_id:extra._id||`call-${status}-${ageMs}`,status,callType:"repository",mediaMode:"audio",startedAt:new Date(now-ageMs),createdAt:new Date(now-ageMs),updatedAt:new Date(now-ageMs),maxParticipants:4,initiatedBy:"u1",...extra,save:async function(){return this;},toObject(){return{...this,save:undefined,toObject:undefined};}});
const makeParticipant=(call,status="joined",extra={})=>({_id:extra._id||`participant-${call._id}`,call,user:extra.user||"u1",status,updatedAt:extra.updatedAt||call.updatedAt,joinedAt:extra.joinedAt||call.startedAt,lastConnectionState:extra.lastConnectionState||"new",save:async function(){return this;},...extra});
function query(rows,{leanRows=rows}={}){return{sort(){return this;},populate(){return this;},limit(){return this;},lean:async()=>leanRows,then(resolve,reject){return Promise.resolve(rows).then(resolve,reject);}};}
function dependencies(rows){const calls=new Map(rows.map(row=>[String(row.call._id),row.call])),participants=rows;const ParticipantModel={find(filter){if(filter.call)return query(participants.filter(row=>String(row.call._id)===String(filter.call)),{leanRows:participants.filter(row=>String(row.call._id)===String(filter.call))});return query(participants.filter(row=>String(row.user)===String(filter.user)&&["invited","ringing","joined"].includes(row.status)));},findOne:async filter=>participants.find(row=>String(row.call._id)===String(filter.call)&&String(row.user)===String(filter.user)),updateOne:async(filter,update)=>{const row=participants.find(value=>String(value._id)===String(filter._id));if(row)Object.assign(row,update.$set);return{modifiedCount:row?1:0};},updateMany:async(filter,update)=>{for(const row of participants)if(String(row.call._id)===String(filter.call)&&filter.status.$in.includes(row.status))Object.assign(row,update.$set);},countDocuments:async filter=>participants.filter(row=>String(row.call._id)===String(filter.call)&&row.status==="joined"&&String(row._id)!==String(filter._id?.$ne||"")).length,distinct:async()=>[...new Set(participants.filter(row=>["invited","ringing","joined"].includes(row.status)).map(row=>row.user))],create:async value=>{const row=Array.isArray(value)?value[0]:value;participants.push(row);return row;}};const CallModel={findById:async id=>calls.get(String(id)),findOneAndUpdate:async(filter,update)=>{const call=calls.get(String(filter._id));if(!call||call.status!==filter.status)return null;Object.assign(call,update.$set);return call;},updateOne:async(filter,update)=>{const call=calls.get(String(filter._id));if(call)Object.assign(call,update.$set);}};return{ParticipantModel,CallModel,isOnline:()=>false,now};}

test("stale initiating calls fail and clear participant state",async()=>{const call=makeCall("initiating",31000),row=makeParticipant(call),deps=dependencies([row]);assert.equal(await service.reconcileUserActiveCall("u1",deps),null);assert.equal(call.status,"failed");assert.equal(row.status,"left");});
test("stale ringing calls become missed",async()=>{const call=makeCall("ringing",31000),row=makeParticipant(call,"ringing"),deps=dependencies([row]);assert.equal(await service.reconcileUserActiveCall("u1",deps),null);assert.equal(call.status,"missed");assert.equal(row.status,"missed");});
test("ended and failed calls never block and stale candidate rows are cleared",async()=>{for(const status of["ended","failed"]){const call=makeCall(status),row=makeParticipant(call),deps=dependencies([row]);assert.equal(await service.reconcileUserActiveCall("u1",deps),null);assert.equal(row.status,"left");}});
test("left participants do not remain busy",async()=>{const call=makeCall("active"),row=makeParticipant(call,"left"),deps=dependencies([row]);assert.equal(await service.isBusy("u1",deps),false);});
test("valid online active calls are recoverable",async()=>{const call=makeCall("active",300000),row=makeParticipant(call,"joined",{lastConnectionState:"connected"}),deps={...dependencies([row]),isOnline:()=>true};const active=await service.reconcileUserActiveCall("u1",deps);assert.equal(String(active._id),String(call._id));assert.equal(call.status,"active");});
test("offline disconnected calls end after the recovery timeout",async()=>{const call=makeCall("active",120000),row=makeParticipant(call,"joined",{lastConnectionState:"disconnected",updatedAt:new Date(now-61000)}),deps=dependencies([row]);assert.equal(await service.reconcileUserActiveCall("u1",deps),null);assert.equal(row.status,"left");assert.equal(call.status,"ended");});
test("leave and end are idempotent and clear active participant state",async()=>{const call=makeCall("active"),row=makeParticipant(call),deps=dependencies([row]);await service.leaveCall(call._id,"u1",deps);await service.leaveCall(call._id,"u1",deps);assert.equal(row.status,"left");assert.equal(call.status,"ended");const second=await service.endCall(call._id,"u1","participant_ended",deps);assert.equal(second.status,"ended");});
test("rejoin after refresh reuses the unique participant",async()=>{const call=makeCall("active"),row=makeParticipant(call),deps={...dependencies([row]),isOnline:()=>true};const before=deps.ParticipantModel.create;let creates=0;deps.ParticipantModel.create=async value=>{creates+=1;return before(value);};await service.joinCall(call._id,"u1",{},deps);assert.equal(creates,0);assert.equal(row.status,"joined");});
test("multiple candidate calls return one and clear the older duplicate",async()=>{const older=makeCall("active",5000,{_id:"older"}),newer=makeCall("active",1000,{_id:"newer"}),rows=[makeParticipant(older,"joined",{_id:"p-old"}),makeParticipant(newer,"joined",{_id:"p-new"})],deps={...dependencies(rows),isOnline:()=>true};const active=await service.reconcileUserActiveCall("u1",deps);assert.equal(String(active._id),"newer");assert.equal(rows[0].status,"left");});
test("concurrent initiation creates only one call for a caller",async()=>{const calls=[],participants=[];const CallModel={create:async value=>{await new Promise(resolve=>setImmediate(resolve));const call=makeCall(value.status,0,{...value,_id:`created-${calls.length+1}`});calls.push(call);return call;}};const ParticipantModel={find:filter=>{const rows=participants.filter(row=>String(row.user)===String(filter.user)&&["invited","ringing","joined"].includes(row.status)).map(row=>({...row,call:calls.find(call=>String(call._id)===String(row.call))}));return query(rows);},create:async rows=>{for(const row of rows)participants.push({...row,_id:`participant-${participants.length+1}`,updatedAt:now});return rows;},updateOne:async()=>({modifiedCount:0}),updateMany:async()=>{},countDocuments:async()=>0};const deps={CallModel,ParticipantModel,ConversationModel:{findOne:async()=>({_id:"conversation-1"})},MemberModel:{find:()=>({lean:async()=>[{user:"u1"},{user:"u2"}]})},BlockModel:{exists:async()=>false},isOnline:()=>true};const results=await Promise.allSettled([service.createDirectCall("u1","u2",{allowOffline:true},deps),service.createDirectCall("u1","u2",{allowOffline:true},deps)]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);assert.equal(results.find(result=>result.status==="rejected").reason.code,"CALL_ALREADY_ACTIVE");assert.equal(calls.length,1);});
test("restart reconciliation visits every candidate user",async()=>{const first=makeCall("active",0,{_id:"first"}),second=makeCall("active",0,{_id:"second"}),rows=[makeParticipant(first,"joined",{user:"u1"}),makeParticipant(second,"joined",{user:"u2"})],deps={...dependencies(rows),isOnline:()=>true};const active=await service.reconcileAllActiveCalls(deps);assert.equal(active.length,2);});
test("repository conversations have unique identity and idempotent creation",async()=>{assert.ok(Conversation.schema.indexes().some(([fields,options])=>fields.type===1&&fields.repository===1&&options.unique));const repositoryId="507f1f77bcf86cd799439011",userId="507f1f77bcf86cd799439012";let stored=null,updates=0;const ConversationModel={findOneAndUpdate:async(filter,update)=>{updates+=1;stored||={_id:"507f1f77bcf86cd799439013",...update.$setOnInsert};return stored;}},MemberModel={updateOne:async()=>{}},deps={ConversationModel,MemberModel,repositoryDependencies:{RepositoryModel:{findById:async()=>({_id:repositoryId,owner:userId,visibility:"public"})},MemberModel:{findOne:async()=>null}}};const one=await chat.ensureContextConversation("repository",repositoryId,userId,deps),two=await chat.ensureContextConversation("repository",repositoryId,userId,deps);assert.equal(one._id,two._id);assert.equal(updates,2);});
test("different repositories may each retain their own General conversation",()=>{const first=new Conversation({type:"repository",repository:"507f1f77bcf86cd799439011",createdBy:"507f1f77bcf86cd799439012",title:"General"}),second=new Conversation({type:"repository",repository:"507f1f77bcf86cd799439013",createdBy:"507f1f77bcf86cd799439012",title:"General"});assert.notEqual(String(first.repository),String(second.repository));assert.equal(first.title,second.title);});
