const callService=require("../services/callService"),permission=require("../services/callPermissionService"),presence=require("../services/presenceService"),Participant=require("../models/callParticipantModel"),{assertRate}=require("../services/chatRateLimitService");
const timers=new Map(),recoveryTimers=new Map(),callRoom=callId=>`call:${callId}`,id=permission.id;
const ackError=(ack,error)=>typeof ack==="function"&&ack({success:false,error:error.code||"CALL_ERROR",message:error.status?error.message:"Unable to complete call request"});
const succeed=(ack,data={})=>typeof ack==="function"&&ack({success:true,...data,data});
const emitCall=(namespace,callId,event,data)=>namespace.to(callRoom(callId)).emit(event,data);
const clearCallTimer=callId=>{const key=id(callId),timer=timers.get(key);if(timer)clearTimeout(timer);timers.delete(key);};
function scheduleMissed(namespace,callId,delay=30000){clearCallTimer(callId);const timer=setTimeout(async()=>{timers.delete(id(callId));try{const call=await callService.markCallMissed(callId);if(call){emitCall(namespace,callId,"call:missed",call);for(const participant of call.participants||[])namespace.to(`user:${id(participant.user)}`).emit("call:missed",call);}}catch{}},delay);timer.unref?.();timers.set(id(callId),timer);}
async function joinedTarget(callId,targetUserId){const participant=await Participant.findOne({call:callId,user:targetUserId,status:"joined"});if(!participant)throw permission.error("CALL_FORBIDDEN","The signalling recipient is not in this call");return participant;}
function assertPayloadSize(value,max,code="CALL_INVALID_STATE"){const length=Buffer.byteLength(typeof value==="string"?value:JSON.stringify(value||{}));if(!length||length>max)throw permission.error(code,"Signalling payload is invalid",400);}

function installCallHandlers(namespace,socket){
  const userId=socket.userId;
  clearTimeout(recoveryTimers.get(id(userId)));recoveryTimers.delete(id(userId));
  callService.reconcileUserActiveCall(userId).then(call=>{if(!call)return;socket.join(callRoom(call._id));socket.emit("call:recovery",call);}).catch(()=>{});
  const handle=(event,fn)=>socket.on(event,async(payload={},ack)=>{try{await fn(payload,ack);}catch(error){ackError(ack,error);}});
  const joinSocket=call=>socket.join(callRoom(call._id||call.id));

  handle("call:initiate",async(payload,ack)=>{assertRate(`call:all:${userId}`,30,3600000);let call;if(payload.callType&&payload.callType!=="direct")call=await callService.createContextualCall(userId,payload);else{assertRate(`call:direct:${userId}:${payload.recipientId}`,10,3600000);call=await callService.createDirectCall(userId,payload.recipientId,payload);}joinSocket(call);const callId=id(call);if(call.callType==="direct"){scheduleMissed(namespace,callId);const recipient=(call.participants||[]).find(value=>id(value.user)!==id(userId));namespace.to(`user:${id(recipient?.user)}`).emit("call:incoming",call);socket.emit("call:ringing",call);}else socket.emit("call:started",call);succeed(ack,{callId,call});});
  handle("call:accept",async(payload,ack)=>{const call=await callService.acceptCall(payload.callId,userId,payload);clearCallTimer(payload.callId);joinSocket(call);emitCall(namespace,payload.callId,"call:accepted",call);succeed(ack,{callId:id(call),call});});
  handle("call:reject",async(payload,ack)=>{const call=await callService.rejectCall(payload.callId,userId);clearCallTimer(payload.callId);emitCall(namespace,payload.callId,"call:rejected",call);namespace.to(`user:${id(call.initiatedBy)}`).emit("call:rejected",call);succeed(ack,{callId:id(call),call});});
  handle("call:cancel",async(payload,ack)=>{const call=await callService.cancelCall(payload.callId,userId);clearCallTimer(payload.callId);emitCall(namespace,payload.callId,"call:cancelled",call);for(const participant of call.participants||[])namespace.to(`user:${id(participant.user)}`).emit("call:cancelled",call);succeed(ack,{callId:id(call),call});});
  handle("call:end",async(payload,ack)=>{const call=await callService.endCall(payload.callId,userId,payload.reason);clearCallTimer(payload.callId);clearTimeout(recoveryTimers.get(id(userId)));recoveryTimers.delete(id(userId));emitCall(namespace,payload.callId,"call:ended",call);succeed(ack,{callId:id(call),call});});
  for(const event of ["call:join","call:rejoin"])handle(event,async(payload,ack)=>{const call=await callService.joinCall(payload.callId,userId,payload);joinSocket(call);emitCall(namespace,payload.callId,"call:participant-joined",{callId:id(call),userId,participants:call.participants});succeed(ack,{callId:id(call),call});});
  handle("call:leave",async(payload,ack)=>{const call=await callService.leaveCall(payload.callId,userId);clearTimeout(recoveryTimers.get(id(userId)));recoveryTimers.delete(id(userId));socket.leave(callRoom(payload.callId));emitCall(namespace,payload.callId,"call:participant-left",{callId:payload.callId,userId,call});succeed(ack,{callId:id(call),call});});
  handle("call:invite",async(payload,ack)=>{assertRate(`call:invite:${userId}`,20,3600000);const participant=await callService.inviteParticipant(payload.callId,userId,payload.userId||payload.username),inviteeId=id(participant.user),call=await callService.getCallById(payload.callId,inviteeId);namespace.to(`user:${inviteeId}`).emit("call:invite-received",{...call,invitation:true});succeed(ack,{callId:payload.callId,participant});});
  handle("call:remove-participant",async(payload,ack)=>{const participant=await callService.removeParticipant(payload.callId,userId,payload.userId);namespace.to(`user:${id(payload.userId)}`).emit("call:access-revoked",{callId:payload.callId,error:"CALL_ACCESS_REVOKED"});namespace.in(`user:${id(payload.userId)}`).socketsLeave(callRoom(payload.callId));emitCall(namespace,payload.callId,"call:participant-left",{callId:payload.callId,userId:id(payload.userId),removed:true});succeed(ack,{callId:payload.callId,participant});});

  const relay=(event,max)=>handle(event,async(payload,ack)=>{assertRate(`signal:${userId}:${payload.callId}`,80,10000);assertPayloadSize(payload.description||payload.candidate,max);const {call,participant}=await permission.assertParticipant(payload.callId,userId);if(call.status!=="active"||participant.status!=="joined")throw permission.error("CALL_NOT_ACTIVE","Join the active call before signalling",409);await joinedTarget(call._id,payload.to);namespace.to(`user:${id(payload.to)}`).emit(event,{callId:id(call),from:userId,...(event==="webrtc:ice-candidate"?{candidate:payload.candidate}:{description:payload.description})});succeed(ack,{callId:id(call)});});
  relay("webrtc:offer",65536);relay("webrtc:answer",65536);relay("webrtc:ice-candidate",4096);relay("webrtc:renegotiate",65536);

  for(const [event,key] of [["media:microphone","microphoneEnabled"],["media:camera","cameraEnabled"],["media:device-change","lastConnectionState"]])handle(event,async(payload,ack)=>{const patch=event==="media:device-change"?{}:{[key]:Boolean(payload.enabled)},participant=await callService.updateParticipant(payload.callId,userId,patch);emitCall(namespace,payload.callId,"media:state-changed",{callId:payload.callId,userId,participant,deviceKind:payload.deviceKind||null});succeed(ack,{callId:payload.callId,participant});});
  for(const [event,active,resultEvent] of [["media:screen-start",true,"media:screen-started"],["media:screen-stop",false,"media:screen-stopped"]])handle(event,async(payload,ack)=>{const value=await callService.setScreenShare(payload.callId,userId,active);emitCall(namespace,payload.callId,resultEvent,{callId:payload.callId,userId});succeed(ack,{callId:payload.callId,participant:value.participant});});
  for(const [event,raised,resultEvent] of [["call:hand-raise",true,"call:hand-raised"],["call:hand-lower",false,"call:hand-lowered"]])handle(event,async(payload,ack)=>{const participant=await callService.updateParticipant(payload.callId,userId,{handRaised:raised});emitCall(namespace,payload.callId,resultEvent,{callId:payload.callId,userId,participant});succeed(ack,{callId:payload.callId,participant});});
  handle("call:quality-report",async(payload,ack)=>{const quality=["excellent","good","fair","poor","reconnecting"].includes(payload.quality)?payload.quality:"unknown",connectionState=["new","connecting","connected","disconnected","failed","closed"].includes(payload.connectionState)?payload.connectionState:undefined;if(connectionState)await callService.updateParticipant(payload.callId,userId,{lastConnectionState:connectionState});else await permission.assertParticipant(payload.callId,userId);emitCall(namespace,payload.callId,"call:quality-updated",{callId:payload.callId,userId,quality});succeed(ack,{callId:payload.callId,quality});});
  socket.on("disconnect",async()=>{if(presence.count(userId)>0)return;try{const active=await callService.getActiveCallForUser(userId,{isOnline:()=>true});if(!active)return;await callService.updateParticipant(active._id,userId,{lastConnectionState:"disconnected"});const key=id(userId),timer=setTimeout(()=>{recoveryTimers.delete(key);callService.reconcileUserActiveCall(userId).catch(()=>{});},callService.RECOVERY_TIMEOUT_MS+50);timer.unref?.();recoveryTimers.set(key,timer);}catch{}});
}
module.exports={installCallHandlers,scheduleMissed,clearCallTimer,assertPayloadSize,timers,recoveryTimers};
