const chat=require("../services/chatService"),permission=require("../services/chatPermissionService"),presence=require("../services/presenceService"),Block=require("../models/chatBlockModel"),{assertRate}=require("../services/chatRateLimitService");
const typing=new Map(),activeViews=new Map();const room=id=>`conversation:${id}`;const ackError=(ack,e)=>typeof ack==="function"&&ack({success:false,error:e.code||"CHAT_ERROR",message:e.status?e.message:"Unable to complete chat request"});
const viewing=(user,conversation)=>activeViews.get(String(user))?.has(String(conversation))||false;
function installChatHandlers(namespace,socket){const userId=socket.userId;presence.connect(userId,socket.id);socket.join(`user:${userId}`);
 const stopTyping=(conversationId,broadcast=true)=>{const key=`${conversationId}:${userId}`,timer=typing.get(key);if(timer)clearTimeout(timer);typing.delete(key);if(broadcast)socket.to(room(conversationId)).emit("typing:stopped",{conversationId,userId});};
 socket.on("conversation:join",async(payload={},ack)=>{try{const access=await permission.assertCanViewConversation(payload.conversationId,userId);socket.join(room(access.conversation._id));const set=activeViews.get(userId)||new Set();set.add(String(access.conversation._id));activeViews.set(userId,set);const newer=payload.afterSequence?await chat.listMessages(access.conversation._id,userId,{after:payload.afterSequence,limit:100}):{messages:[]};const data={conversationId:String(access.conversation._id),messages:newer.messages};socket.emit("conversation:joined",data);ack?.({success:true,data});}catch(e){ackError(ack,e);}});
 socket.on("conversation:leave",(payload={},ack)=>{socket.leave(room(payload.conversationId));activeViews.get(userId)?.delete(String(payload.conversationId));stopTyping(payload.conversationId);ack?.({success:true,data:{}});});
 socket.on("message:send",async(payload={},ack)=>{try{assertRate(`message:${userId}`,30,60000);const message=await chat.sendMessage(payload.conversationId,userId,payload,{isActivelyViewing:viewing});namespace.to(room(payload.conversationId)).emit("message:new",message);ack?.({success:true,data:{message}});}catch(e){ackError(ack,e);}});
 socket.on("message:edit",async(payload={},ack)=>{try{const message=await chat.editMessage(payload.messageId,userId,payload.content);namespace.to(room(message.conversation)).emit("message:updated",message);ack?.({success:true,data:{message}});}catch(e){ackError(ack,e);}});
 socket.on("message:delete",async(payload={},ack)=>{try{const message=await chat.deleteMessage(payload.messageId,userId);namespace.to(room(message.conversation)).emit("message:deleted",message);ack?.({success:true,data:{message}});}catch(e){ackError(ack,e);}});
 socket.on("message:read",async(payload={},ack)=>{try{const state=await chat.markRead(payload.conversationId,userId,payload.sequence);namespace.to(room(payload.conversationId)).emit("message:read_updated",{conversationId:payload.conversationId,userId,...state});ack?.({success:true,data:state});}catch(e){ackError(ack,e);}});
 for(const [event,remove] of [["reaction:add",false],["reaction:remove",true]])socket.on(event,async(payload={},ack)=>{try{const result=await chat.setReaction(payload.messageId,userId,payload.emoji,remove);namespace.to(room(result.conversationId)).emit("reaction:updated",{messageId:payload.messageId,reactions:result.reactions});ack?.({success:true,data:{reactions:result.reactions}});}catch(e){ackError(ack,e);}});
 socket.on("typing:start",async(payload={},ack)=>{try{assertRate(`typing:${userId}:${payload.conversationId}`,1,900);await permission.assertCanSendMessage(payload.conversationId,userId);const key=`${payload.conversationId}:${userId}`;clearTimeout(typing.get(key));socket.to(room(payload.conversationId)).emit("typing:started",{conversationId:payload.conversationId,user:{_id:userId,username:socket.user.username}});typing.set(key,setTimeout(()=>stopTyping(payload.conversationId),5000));ack?.({success:true,data:{}});}catch(e){ackError(ack,e);}});socket.on("typing:stop",payload=>stopTyping(payload?.conversationId));
 socket.on("presence:subscribe",async(payload={},ack)=>{try{await permission.assertCanViewConversation(payload.conversationId,userId);const target=String(payload.userId||"");if(await Block.exists({$or:[{blocker:userId,blocked:target},{blocker:target,blocked:userId}]}))throw permission.error("FORBIDDEN","Presence is unavailable");socket.join(`presence:${target}`);const data={userId:target,online:presence.isOnline(target)};socket.emit("presence:changed",data);ack?.({success:true,data});}catch(e){ackError(ack,e);}});
 socket.on("presence:unsubscribe",(payload={},ack)=>{socket.leave(`presence:${String(payload.userId||"")}`);ack?.({success:true,data:{}});});
 socket.on("disconnect",()=>{for(const conversationId of activeViews.get(userId)||[])stopTyping(conversationId);activeViews.delete(userId);presence.disconnect(userId,socket.id,{onOffline:data=>namespace.to(`presence:${userId}`).emit("presence:changed",{...data,online:false})});});
}
module.exports={installChatHandlers,typing,activeViews,viewing};
