const express = require("express");
const multer = require("multer");

const repoController = require("../controllers/repoController");
const { pushRepo } = require("../controllers/push");
const { addFiles } = require("../controllers/addController");
const { createCommit } = require("../controllers/commitController");
const { getFile } = require("../controllers/fileController");
const { pullRepo } = require("../controllers/pull");
const { getCommitHistory } = require("../controllers/historyController");
const { getCommitDiff } = require("../controllers/diffController");
const { previewFile } = require("../controllers/previewController");
const { deleteFile, renameFile } = require("../controllers/fileManageController");
const { listBranches, createBranch, deleteBranch } = require("../controllers/branchController");
const { getSnapshot, getSnapshotFile } = require("../controllers/snapshotController");
const { compareBranches } = require("../controllers/compareController");
const pullRequestController = require("../controllers/pullRequestController");
const advancedReviewController = require("../controllers/advancedReviewController");
const repositoryInsightsController = require("../controllers/repositoryInsightsController");
const issueController = require("../controllers/issueController");
const socialController = require("../controllers/repositorySocialController");
const fileEditController = require("../controllers/fileEditController");
const publicDiscoveryController = require("../controllers/publicDiscoveryController");
const collaboratorController = require("../controllers/repositoryCollaboratorController");
const branchProtectionController = require("../controllers/branchProtectionController");
const repositoryCliController = require("../controllers/repositoryCliController");
const { optionalAuth, requireAuth } = require("../middleware/authMiddleware");
const repositoryAccess = require("../utils/repositoryAccess");
const { requireRepositoryRead, requireRepositoryWrite } = repositoryAccess;
const requireRepositoryPermission = repositoryAccess.requireRepositoryPermission
  || (() => requireRepositoryWrite);

const repoRouter = express.Router();
const upload = multer({ dest: "uploads/" });
const cliUpload = multer({ dest: "uploads/", limits: { fileSize: 25 * 1024 * 1024, files: 500, fields: 20 } });
const receiveCliPush = (req, res, next) => cliUpload.array("files")(req, res, (error) => {
  if (!error) return next();
  const tooLarge = error.code === "LIMIT_FILE_SIZE" || error.code === "LIMIT_FILE_COUNT";
  return res.status(tooLarge ? 413 : 400).json({ error: tooLarge ? "Push exceeds the configured file limits" : "Invalid push upload", code: tooLarge ? "FILE_TOO_LARGE" : "INVALID_PUSH" });
});

// Existing write workflows.
repoRouter.post("/add/:id", requireRepositoryWrite, upload.array("files"), addFiles);
repoRouter.post("/commit/:id", requireRepositoryWrite, createCommit);
repoRouter.post("/push/:id", requireRepositoryWrite, pushRepo);
repoRouter.post("/pull/:id", requireRepositoryWrite, pullRepo);
repoRouter.post("/create", requireAuth, repoController.createRepository);
repoRouter.post("/:id/star", requireAuth, requireRepositoryRead, socialController.star);
repoRouter.delete("/:id/star", requireAuth, requireRepositoryRead, socialController.unstar);
repoRouter.get("/:id/star-status", optionalAuth, requireRepositoryRead, socialController.status);
repoRouter.post("/:id/watch", requireAuth, requireRepositoryRead, socialController.watch);
repoRouter.delete("/:id/watch", requireAuth, requireRepositoryRead, socialController.unwatch);
repoRouter.get("/:id/watch-status", optionalAuth, requireRepositoryRead, socialController.status);
repoRouter.post("/:id/fork", requireAuth, requireRepositoryRead, socialController.fork);
repoRouter.get("/:id/file-editor", requireRepositoryWrite, fileEditController.read);
repoRouter.post("/:id/file-editor", requireRepositoryWrite, fileEditController.create);
repoRouter.put("/:id/file-editor", requireRepositoryWrite, fileEditController.update);
repoRouter.get("/:id/branch-protection", requireAuth, requireRepositoryPermission("manage_branch_protection"), branchProtectionController.list);
repoRouter.post("/:id/branch-protection", requireAuth, requireRepositoryPermission("manage_branch_protection"), branchProtectionController.create);
repoRouter.patch("/:id/branch-protection/:branch", requireAuth, requireRepositoryPermission("manage_branch_protection"), branchProtectionController.update);
repoRouter.delete("/:id/branch-protection/:branch", requireAuth, requireRepositoryPermission("manage_branch_protection"), branchProtectionController.remove);
repoRouter.post("/:id/collaborators/invitations", requireAuth, requireRepositoryPermission("manage_collaborators"), collaboratorController.invite);
repoRouter.get("/:id/collaborators", requireAuth, requireRepositoryRead, collaboratorController.listCollaborators);
repoRouter.get("/:id/collaborators/invitations", requireAuth, requireRepositoryPermission("manage_collaborators"), collaboratorController.listRepositoryInvitations);
repoRouter.patch("/:id/collaborators/:userId", requireAuth, requireRepositoryPermission("manage_collaborators"), collaboratorController.updateRole);
repoRouter.delete("/:id/collaborators/:userId", requireAuth, requireRepositoryPermission("manage_collaborators"), collaboratorController.remove);
repoRouter.delete("/:id/collaborators/invitations/:invitationId", requireAuth, requireRepositoryPermission("manage_collaborators"), collaboratorController.cancel);

// Branch, history, and clone/snapshot APIs. Keep these before /:id.
repoRouter.get("/explore", publicDiscoveryController.explore);
repoRouter.get("/resolve/:owner/:name", optionalAuth, repositoryCliController.resolve);
repoRouter.get("/:id/cli/metadata", optionalAuth, requireRepositoryRead, repositoryCliController.metadata);
repoRouter.get("/:id/cli/fetch", optionalAuth, requireRepositoryRead, repositoryCliController.metadata);
repoRouter.post("/:id/cli/push", requireAuth, requireRepositoryWrite, receiveCliPush, repositoryCliController.push);
repoRouter.get("/:id/compare", compareBranches);
repoRouter.post("/:id/issues", requireAuth, requireRepositoryRead, issueController.create);
repoRouter.get("/:id/issues", optionalAuth, requireRepositoryRead, issueController.list);
repoRouter.get("/:id/issues/:number", optionalAuth, requireRepositoryRead, issueController.details);
repoRouter.patch("/:id/issues/:number", requireAuth, requireRepositoryRead, issueController.update);
repoRouter.post("/:id/issues/:number/comments", requireAuth, requireRepositoryRead, issueController.comment);
repoRouter.post("/:id/issues/:number/close", requireAuth, requireRepositoryRead, issueController.close);
repoRouter.post("/:id/issues/:number/reopen", requireAuth, requireRepositoryRead, issueController.reopen);
repoRouter.post("/:id/issues/:number/labels", requireAuth, requireRepositoryRead, issueController.addLabel);
repoRouter.delete("/:id/issues/:number/labels/:labelName", requireAuth, requireRepositoryRead, issueController.removeLabel);
repoRouter.post("/:id/issues/:number/assignees", requireAuth, requireRepositoryRead, issueController.addAssignee);
repoRouter.delete("/:id/issues/:number/assignees/:userId", requireAuth, requireRepositoryRead, issueController.removeAssignee);
repoRouter.post("/:id/issues/:number/link-pr", requireAuth, requireRepositoryRead, issueController.linkPullRequest);
repoRouter.post("/:id/pulls", requireAuth, requireRepositoryRead, pullRequestController.create);
repoRouter.get("/:id/pulls", optionalAuth, requireRepositoryRead, pullRequestController.list);
repoRouter.get("/:id/pulls/:number", optionalAuth, requireRepositoryRead, pullRequestController.details);
repoRouter.patch("/:id/pulls/:number", requireAuth, requireRepositoryRead, pullRequestController.update);
repoRouter.post("/:id/pulls/:number/comments", requireAuth, requireRepositoryRead, pullRequestController.comment);
repoRouter.get("/:id/pulls/:number/reviews", optionalAuth, requireRepositoryRead, pullRequestController.listReviews);
repoRouter.post("/:id/pulls/:number/reviews", requireAuth, requireRepositoryRead, pullRequestController.review);
repoRouter.get("/:id/pulls/:number/reviewers", optionalAuth, requireRepositoryRead, advancedReviewController.reviewers);
repoRouter.post("/:id/pulls/:number/reviewers", requireAuth, requireRepositoryRead, advancedReviewController.requestReviewer);
repoRouter.delete("/:id/pulls/:number/reviewers/:userId", requireAuth, requireRepositoryRead, advancedReviewController.removeReviewer);
repoRouter.get("/:id/pulls/:number/files", optionalAuth, requireRepositoryRead, advancedReviewController.files);
repoRouter.post("/:id/pulls/:number/threads", requireAuth, requireRepositoryRead, advancedReviewController.createThread);
repoRouter.post("/:id/pulls/:number/threads/:threadId/comments", requireAuth, requireRepositoryRead, advancedReviewController.reply);
repoRouter.patch("/:id/pulls/:number/comments/:commentId", requireAuth, requireRepositoryRead, advancedReviewController.editComment);
repoRouter.delete("/:id/pulls/:number/comments/:commentId", requireAuth, requireRepositoryRead, advancedReviewController.deleteComment);
repoRouter.patch("/:id/pulls/:number/threads/:threadId/resolve", requireAuth, requireRepositoryRead, advancedReviewController.resolve);
repoRouter.patch("/:id/pulls/:number/threads/:threadId/reopen", requireAuth, requireRepositoryRead, advancedReviewController.reopen);
repoRouter.get("/:id/pulls/:number/merge-status", optionalAuth, requireRepositoryRead, advancedReviewController.mergeStatus);
repoRouter.get("/:id/insights/overview", optionalAuth, repositoryInsightsController.overview);
repoRouter.get("/:id/insights/commits", optionalAuth, repositoryInsightsController.commits);
repoRouter.get("/:id/insights/contributors", optionalAuth, repositoryInsightsController.contributors);
repoRouter.get("/:id/insights/languages", optionalAuth, repositoryInsightsController.languages);
repoRouter.get("/:id/insights/issues", optionalAuth, repositoryInsightsController.issues);
repoRouter.get("/:id/insights/pull-requests", optionalAuth, repositoryInsightsController.pullRequests);
repoRouter.get("/:id/insights/branches", optionalAuth, repositoryInsightsController.branches);
repoRouter.get("/:id/insights/activity", optionalAuth, repositoryInsightsController.activity);
repoRouter.get("/:id/insights/files", optionalAuth, repositoryInsightsController.files);
repoRouter.post("/:id/pulls/:number/merge", requireAuth, requireRepositoryPermission("merge_pr"), pullRequestController.merge);
repoRouter.post("/:id/pulls/:number/close", requireAuth, requireRepositoryRead, pullRequestController.close);
repoRouter.post("/:id/pulls/:number/reopen", requireAuth, requireRepositoryRead, pullRequestController.reopen);
repoRouter.get("/:id/branches", listBranches);
repoRouter.post("/:id/branches", requireRepositoryWrite, createBranch);
repoRouter.get("/:id/branches/:branchName/snapshot", getSnapshot);
repoRouter.get("/:id/branches/:branchName/history", getCommitHistory);
repoRouter.delete("/:id/branches/:branchName", deleteBranch);
repoRouter.get("/:id/history", getCommitHistory);
repoRouter.get("/:id/history/:branchName", getCommitHistory);
repoRouter.get("/:id/commit/:commitId/diff", getCommitDiff);
repoRouter.get("/:id/snapshot-file", getSnapshotFile);
repoRouter.get("/:id/snapshot", getSnapshot);
repoRouter.get("/:id/snapshot/:branchName", getSnapshot);

// Legacy history URL remains supported.
repoRouter.get("/history/:id", getCommitHistory);

repoRouter.get("/all", optionalAuth, repoController.getAllRepositories);
repoRouter.get("/name/:name", optionalAuth, repoController.fetchRepositoryByName);
repoRouter.get("/user/:userID", requireAuth, repoController.fetchRepositoriesForCurrentUser);
repoRouter.put("/update/:id", requireRepositoryWrite, repoController.updateRepositoryById);
repoRouter.delete("/delete/:id", requireRepositoryPermission("delete_repository"), repoController.deleteRepositoryById);
repoRouter.patch("/toggle/:id", requireRepositoryPermission("change_visibility"), repoController.toggleVisibilityById);
// Express 4 wildcard routes preserve complete nested repository paths in req.params[0].
repoRouter.get("/preview/:id/*", previewFile);
repoRouter.get("/file/:id/*", getFile);
repoRouter.put("/file/:id/*", requireRepositoryWrite, renameFile);
repoRouter.delete("/file/:id/*", requireRepositoryWrite, deleteFile);
repoRouter.get("/:id", optionalAuth, requireRepositoryRead, repoController.fetchRepositoryById);

module.exports = repoRouter;
