const mongoose=require("mongoose"),Conversation=require("../models/conversationModel"),Member=require("../models/conversationMemberModel"),Message=require("../models/chatMessageModel"),Reaction=require("../models/messageReactionModel"),Block=require("../models/chatBlockModel"),Report=require("../models/chatReportModel"),MentorRequest=require("../models/mentorRequestModel"),Repository=require("../models/repoModel"),Issue=require("../models/issueModel"),PullRequest=require("../models/pullRequestModel"),User=require("../models/userModel");
const chat=require("../services/chatService"),permission=require("../services/chatPermissionService"),{assertRate}=require("../services/chatRateLimitService"),{resolveRepositoryPermissionContext}=require("../services/repositoryPermissionService"),{createNotification}=require("../services/notificationService");
const attachmentService=require("../services/chatAttachmentService");
const voiceService=require("../services/voiceMessageService");
const id=v=>String(v?._id||v?.id||v||"");const valid=v=>mongoose.Types.ObjectId.isValid(v);const sendError=(res,e)=>res.status(e.status||500).json({success:false,error:e.code||"CHAT_ERROR",message:e.status?e.message:"Unable to complete chat request"});
const endpoint=fn=>async(req,res)=>{try{return res.json({success:true,...await fn(req,res)});}catch(e){return sendError(res,e);}};
const list=endpoint(async req=>({conversations:await chat.listConversations(req.user.id)}));
const direct=endpoint(async req=>{if(!valid(req.params.userId))throw permission.error("USER_NOT_FOUND","User not found",404);assertRate(`direct:${req.user.id}`,10,3600000);return{conversation:await chat.createDirect(req.user.id,req.params.userId)};});
const details=endpoint(async req=>{const access=await permission.assertCanViewConversation(req.params.conversationId,req.user.id);const member=await Member.findOne({conversation:access.conversation._id,user:req.user.id}).lean();return{conversation:access.conversation,member,unreadCount:Math.max(0,(access.conversation.lastSequence||0)-(member?.lastReadSequence||0))};});
const messages=endpoint(async req=>chat.listMessages(req.params.conversationId,req.user.id,req.query));
const send=endpoint(async req=>{assertRate(`message:${req.user.id}`,30,60000);return{message:await chat.sendMessage(req.params.conversationId,req.user.id,req.body||{})};});
const attachmentUpload=endpoint(async req=>{assertRate(`attachment:${req.user.id}`,20,3600000);const value=await attachmentService.upload(req.file,req.user.id);return{attachment:{_id:value._id,originalName:value.originalName,mimeType:value.mimeType,size:value.size}};});
async function attachmentDownload(req,res){try{const value=await attachmentService.download(req.params.messageId,req.params.attachmentId,req.user.id);res.setHeader("Content-Type",value.attachment.mimeType);res.setHeader("Content-Disposition",`attachment; filename*=UTF-8''${encodeURIComponent(value.attachment.originalName)}`);res.setHeader("Cache-Control","private, no-store");return res.send(value.body);}catch(e){return sendError(res,e);}}
const edit=endpoint(async req=>({message:await chat.editMessage(req.params.messageId,req.user.id,req.body?.content)}));
const remove=endpoint(async req=>{const message=await Message.findById(req.params.messageId).select("messageType");return{message:message?.messageType==="voice"?await voiceService.remove(req.params.messageId,req.user.id):await chat.deleteMessage(req.params.messageId,req.user.id)};});
const voiceUpload=endpoint(async req=>{assertRate(`voice:${req.user.id}`,20,3600000);const message=await voiceService.create(req.params.conversationId,req.user.id,req.file,req.body||{});const {emitConversationEvent}=require("../sockets/socketServer");emitConversationEvent(message.conversation,"message:new",message);return{message};});
async function voicePlayback(req,res){try{const value=await voiceService.load(req.params.messageId,req.user.id);res.setHeader("Content-Type",value.message.voice.mimeType);res.setHeader("Content-Length",value.body.length);res.setHeader("Content-Disposition",`${req.query.download==="1"?"attachment":"inline"}; filename*=UTF-8''${encodeURIComponent(value.message.voice.originalName)}`);res.setHeader("Cache-Control","private, no-store");res.setHeader("Accept-Ranges","none");return res.send(value.body);}catch(e){return sendError(res,e);}}
const read=endpoint(async req=>({readState:await chat.markRead(req.params.conversationId,req.user.id,req.body?.sequence)}));
const search=endpoint(async req=>{assertRate(`search:${req.user.id}`,30,60000);return chat.search(req.params.conversationId,req.user.id,req.query?.q,req.query?.cursor);});
const react=endpoint(async req=>{const value=await chat.setReaction(req.params.messageId,req.user.id,req.body?.emoji);return{reactions:value.reactions};});
const unreact=endpoint(async req=>{const value=await chat.setReaction(req.params.messageId,req.user.id,decodeURIComponent(req.params.emoji),true);return{reactions:value.reactions};});
const block=endpoint(async req=>{if(!valid(req.params.userId)||id(req.params.userId)===id(req.user.id))throw permission.error("CANNOT_MESSAGE_SELF","Invalid blocked user",400);await User.exists({_id:req.params.userId})||(()=>{throw permission.error("USER_NOT_FOUND","User not found",404);})();await Block.updateOne({blocker:req.user.id,blocked:req.params.userId},{$setOnInsert:{createdAt:new Date()}},{upsert:true});return{};});
const unblock=endpoint(async req=>{await Block.deleteOne({blocker:req.user.id,blocked:req.params.userId});return{};});
const blocked=endpoint(async req=>({users:await Block.find({blocker:req.user.id}).populate("blocked","_id username name avatarUrl").lean()}));
const mute=endpoint(async req=>{await permission.assertCanViewConversation(req.params.conversationId,req.user.id);const until=req.body?.duration==="indefinite"?new Date(8640000000000000):new Date(Date.now()+({"1h":3600000,"8h":28800000,"1d":86400000}[req.body?.duration]||0));if(!["1h","8h","1d","indefinite"].includes(req.body?.duration))throw permission.error("INVALID_MUTE","Invalid mute duration",400);const member=await Member.findOneAndUpdate({conversation:req.params.conversationId,user:req.user.id},{$set:{mutedUntil:until},$setOnInsert:{joinedAt:new Date()}},{upsert:true,new:true});return{member};});
const unmute=endpoint(async req=>{const member=await Member.findOneAndUpdate({conversation:req.params.conversationId,user:req.user.id},{$set:{mutedUntil:null}},{new:true});return{member};});
const report=endpoint(async req=>{assertRate(`report:${req.user.id}`,10,86400000);if(!["spam","harassment","inappropriate","threat","sensitive_information","other"].includes(req.body?.reason))throw permission.error("INVALID_REPORT_REASON","Invalid report reason",400);const message=await Message.findById(req.params.messageId);if(!message)throw permission.error("MESSAGE_NOT_FOUND","Message not found",404);await permission.assertCanViewConversation(message.conversation,req.user.id);try{const value=await Report.create({message:message._id,conversation:message.conversation,reportedBy:req.user.id,reason:req.body.reason,details:chat.clean(req.body?.details,2000)});await Message.updateOne({_id:message._id},{$set:{moderationStatus:"under_review"}});return{report:value};}catch(e){if(e.code===11000)throw permission.error("REPORT_ALREADY_EXISTS","Message already reported",409);throw e;}});
async function assertRepositoryModerator(conversation,userId){if(!["repository","issue","pull_request"].includes(conversation?.type))throw permission.error("FORBIDDEN","Private conversation reports require a platform moderator",403);const repositoryId=await permission.repositoryContext(conversation);const access=await resolveRepositoryPermissionContext(repositoryId,userId,{skipExpirationWrite:true});if(!["owner","maintainer"].includes(access.role)||["expired","suspended","not_started"].includes(access.status))throw permission.error("FORBIDDEN","Repository owner or active maintainer access is required",403);return access;}
const reports=endpoint(async req=>{const conversations=await Conversation.find({type:{$in:["repository","issue","pull_request"]},isArchived:false}).lean(),allowed=[];for(const conversation of conversations){try{await assertRepositoryModerator(conversation,req.user.id);allowed.push(conversation._id);}catch{}}const filter={conversation:{$in:allowed}};if(req.query?.status)filter.status=req.query.status;if(req.query?.cursor){if(!valid(req.query.cursor))throw permission.error("INVALID_CURSOR","Invalid cursor",400);filter._id={$lt:req.query.cursor};}const values=await Report.find(filter).sort({_id:-1}).limit(50).populate("message","sender content messageType createdAt moderationStatus deletedAt").populate("reportedBy","_id username name avatarUrl").lean();return{reports:values,nextCursor:values.length===50?id(values.at(-1)._id):null};});
const reviewReport=endpoint(async req=>{const value=await Report.findById(req.params.reportId);if(!value)throw permission.error("REPORT_NOT_FOUND","Report not found",404);const conversation=await Conversation.findById(value.conversation);await assertRepositoryModerator(conversation,req.user.id);const status=String(req.body?.status||"");if(!["reviewing","resolved","rejected"].includes(status))throw permission.error("INVALID_REPORT_STATUS","Invalid report status",400);value.status=status;value.reviewedBy=req.user.id;value.resolution=chat.clean(req.body?.resolution,2000);await value.save();if(req.body?.hide===true)await Message.updateOne({_id:value.message,conversation:value.conversation},{$set:{moderationStatus:"hidden"}});else if(["resolved","rejected"].includes(status))await Message.updateOne({_id:value.message,conversation:value.conversation},{$set:{moderationStatus:"visible"}});return{report:value};});
const context=type=>endpoint(async req=>{const contextId=type==="repository"?req.params.repoId:type==="issue"?(await Issue.findOne({repository:req.params.repoId,number:Number(req.params.issueId)}).select("_id"))?._id:(await PullRequest.findOne({repository:req.params.repoId,number:Number(req.params.pullRequestId)}).select("_id"))?._id;if(!contextId)throw permission.error(type==="issue"?"ISSUE_NOT_FOUND":"PULL_REQUEST_NOT_FOUND",`${type} not found`,404);return{conversation:await chat.ensureContextConversation(type,contextId,req.user.id)};});
const mentorCreate=endpoint(async req=>{assertRate(`mentor:${req.user.id}`,10,86400000);const repository=await Repository.findById(req.params.repoId);if(!repository)throw permission.error("REPOSITORY_NOT_FOUND","Repository not found",404);const requester=await resolveRepositoryPermissionContext(repository,req.user.id,{skipExpirationWrite:true});if(!requester.role||["expired","suspended","not_started"].includes(requester.status))throw permission.error("FORBIDDEN","Active repository membership is required");const mentor=await resolveRepositoryPermissionContext(repository,req.body?.mentorId,{skipExpirationWrite:true});if(!["owner","maintainer"].includes(mentor.role)||["expired","suspended","not_started"].includes(mentor.status))throw permission.error("MENTOR_NOT_ELIGIBLE","Mentor must be the active owner or maintainer",400);if(req.body?.issueId&&!await Issue.exists({_id:req.body.issueId,repository:repository._id}))throw permission.error("ISSUE_NOT_FOUND","Issue not found",404);try{const request=await MentorRequest.create({repository:repository._id,issue:req.body?.issueId||null,requester:req.user.id,requestedMentor:req.body.mentorId,message:chat.clean(req.body?.message,2000)});await createNotification({recipient:req.body.mentorId,actor:req.user.id,repository:repository._id,type:"mentor_request",title:"Mentor help requested",message:"A repository member requested your help.",url:`/chat`,eventKey:`mentor-request:${request._id}`});return{request};}catch(e){if(e.code===11000)throw permission.error("MENTOR_REQUEST_EXISTS","A pending mentor request already exists",409);throw e;}});
const mentorList=endpoint(async req=>{const repository=await Repository.findById(req.params.repoId);if(!repository)throw permission.error("REPOSITORY_NOT_FOUND","Repository not found",404);const access=await resolveRepositoryPermissionContext(repository,req.user.id,{skipExpirationWrite:true});if(repository.visibility==="private"&&!access.role)throw permission.error("FORBIDDEN","Repository access required");return{requests:await MentorRequest.find({repository:repository._id,$or:[{requester:req.user.id},{requestedMentor:req.user.id}]}).populate("requester requestedMentor","_id username name avatarUrl").lean()};});
const mentorUpdate=endpoint(async req=>{const request=await MentorRequest.findOne({_id:req.params.requestId,repository:req.params.repoId});if(!request)throw permission.error("MENTOR_REQUEST_NOT_FOUND","Mentor request not found",404);const status=req.body?.status;if(status==="accepted"){if(id(request.requestedMentor)!==id(req.user.id)||request.status!=="pending")throw permission.error("FORBIDDEN","Only the requested mentor may accept",403);let conversation=await Conversation.findOne({type:"mentor",repository:request.repository,mentor:request.requestedMentor,mentee:request.requester,mentorStatus:{$in:["active","pending"]}});if(!conversation)conversation=await Conversation.create({type:"mentor",repository:request.repository,mentor:request.requestedMentor,mentee:request.requester,mentorStatus:"active",createdBy:req.user.id,title:"Mentor help"});await Promise.all([[request.requester,"mentee"],[request.requestedMentor,"mentor"]].map(([user,memberRole])=>Member.updateOne({conversation:conversation._id,user},{$setOnInsert:{conversation:conversation._id,user,memberRole,joinedAt:new Date()}},{upsert:true})));request.status="accepted";request.conversation=conversation._id;await request.save();await createNotification({recipient:request.requester,actor:req.user.id,repository:request.repository,type:"mentor_request_accepted",title:"Mentor request accepted",message:"Your mentor request was accepted.",url:`/chat?conversation=${conversation._id}`,eventKey:`mentor-accepted:${request._id}`});return{request,conversation};}if(status==="declined"){if(id(request.requestedMentor)!==id(req.user.id))throw permission.error("FORBIDDEN","Only the requested mentor may decline");request.status="declined";await request.save();return{request};}if(status==="closed"){if(![id(request.requester),id(request.requestedMentor)].includes(id(req.user.id)))throw permission.error("FORBIDDEN","Only participants may close");request.status="closed";await request.save();if(request.conversation)await Conversation.updateOne({_id:request.conversation},{$set:{mentorStatus:"closed"}});return{request};}throw permission.error("INVALID_MENTOR_STATUS","Invalid mentor status",400);});
module.exports={list,direct,details,messages,send,edit,remove,read,search,react,unreact,block,unblock,blocked,mute,unmute,report,reports,reviewReport,repositoryChat:context("repository"),issueChat:context("issue"),pullChat:context("pull_request"),mentorCreate,mentorList,mentorUpdate,attachmentUpload,attachmentDownload,voiceUpload,voicePlayback,sendError};
