const Call=require("../models/callSessionModel");
const Participant=require("../models/callParticipantModel");
const User=require("../models/userModel");
const Repository=require("../models/repoModel");
const RepositoryMember=require("../models/repositoryMemberModel");
const permission=require("./callPermissionService");
const presence=require("./presenceService");
const {createNotification}=require("./notificationService");

const id=permission.id;
const terminal=new Set(["rejected","cancelled","missed","ended","failed"]);
const transitions={initiating:new Set(["ringing","active","failed"]),ringing:new Set(["active","rejected","cancelled","missed","failed"]),active:new Set(["ended","failed"])};
const INITIATING_TIMEOUT_MS=30000;
const RINGING_TIMEOUT_MS=30000;
const RECOVERY_TIMEOUT_MS=60000;
const CALL_INVITATION_TTL_MS=5*60*1000;
const creationLocks=new Map();

function assertCallTransition(from,to){if(!transitions[from]?.has(to))throw permission.error("CALL_INVALID_STATE",`Cannot change a call from ${from} to ${to}`,409);return true;}
const age=(value,now)=>now-new Date(value||0).getTime();
async function safeCall(call,deps={}){const ParticipantModel=deps.ParticipantModel||Participant,participants=await ParticipantModel.find({call:call._id}).populate("user","_id username name avatarUrl").lean();const raw=call.toObject?call.toObject():{...call};return{...raw,participants};}

async function repositoryForCall(call,deps={}){if(call.callType==="repository")return call.repository;if(call.callType==="issue"){const issue=await(deps.IssueModel||require("../models/issueModel")).findById(call.issue);return issue?.repository;}if(call.callType==="pull_request"){const pull=await(deps.PullModel||require("../models/pullRequestModel")).findById(call.pullRequest);return pull?.repository;}return call.repository||null;}
async function listEligibleInvitees(callId,hostId,deps={}){
  const {call,participant}=await permission.assertParticipant(callId,hostId,deps);
  if(participant.role!=="host"||participant.status!=="joined")throw permission.error("CALL_FORBIDDEN","You do not have permission to invite participants");
  if(call.status!=="active"||call.acceptingParticipants===false)throw permission.error("CALL_NOT_ACTIVE","This call is not accepting invitations",409);
  const repositoryId=await repositoryForCall(call,deps);if(!repositoryId)throw permission.error("CALL_FORBIDDEN","This call does not have repository invitees");
  const context=await(deps.resolveRepositoryPermissionContext||require("./repositoryPermissionService").resolveRepositoryPermissionContext)(repositoryId,hostId,{skipExpirationWrite:true,...deps.repositoryDependencies});
  const MemberModel=deps.RepositoryMemberModel||RepositoryMember,ParticipantModel=deps.ParticipantModel||Participant;
  let query=MemberModel.find({repository:context.repository._id});if(query.populate)query=query.populate("user","_id username name avatarUrl lastSeenAt");if(query.lean)query=query.lean();const memberships=await query;
  const users=new Map();const owner=context.repository.owner;if(owner){const ownerId=id(owner);let ownerUser=typeof owner==="object"&&owner.username?owner:null;if(!ownerUser)ownerUser=await(deps.UserModel||User).findById(ownerId).select?.("_id username name avatarUrl lastSeenAt")||await(deps.UserModel||User).findById(ownerId);if(ownerUser)users.set(ownerId,{user:ownerUser,membership:null});}
  for(const membership of memberships||[])if(membership.user)users.set(id(membership.user),{user:membership.user,membership});
  let participantQuery=ParticipantModel.find({call:call._id});if(participantQuery.lean)participantQuery=participantQuery.lean();const participantRows=await participantQuery,byUser=new Map(participantRows.map(row=>[id(row.user),row.status])),members=[];
  for(const [userId,value] of users){if(userId===id(hostId))continue;let access;try{access=await permission.activeRepositoryInvitee(repositoryId,userId,{...deps,repositoryDependencies:{...deps.repositoryDependencies,membership:value.membership}});}catch{continue;}const user=value.user.toObject?value.user.toObject():value.user;members.push({userId,username:user.username,name:user.name||null,avatarUrl:user.avatarUrl||null,role:access.role,online:(deps.isOnline||presence.isOnline)(userId),temporaryAccessExpiresAt:access.accessExpiresAt||access.membership?.accessExpiresAt||null,invitationStatus:byUser.get(userId)||null});}
  return members.sort((a,b)=>Number(b.online)-Number(a.online)||String(a.username).localeCompare(String(b.username)));
}
async function invitationPayload(callId,invitedUserId,deps={}){const call=await getCallById(callId,invitedUserId,deps),RepositoryModel=deps.RepositoryModel||Repository,UserModel=deps.UserModel||User,repositoryId=await repositoryForCall(call,deps),repository=repositoryId?await RepositoryModel.findById(id(repositoryId)).select?.("_id name")||await RepositoryModel.findById(id(repositoryId)):null,inviter=await UserModel.findById(id(call.initiatedBy)).select?.("_id username name avatarUrl")||await UserModel.findById(id(call.initiatedBy)),invitedParticipant=(call.participants||[]).find(value=>id(value.user)===id(invitedUserId));return{_id:id(call),invitationId:id(invitedParticipant),callId:id(call),callType:call.callType,mediaMode:call.mediaMode,status:call.status,startedAt:call.startedAt,answeredAt:call.answeredAt,maxParticipants:call.maxParticipants,invitation:true,expiresAt:invitedParticipant?.invitationExpiresAt||null,repository:repository?{_id:id(repository),name:repository.name}:null,initiatedBy:inviter?{_id:id(inviter),username:inviter.username,name:inviter.name||null,avatarUrl:inviter.avatarUrl||null}:{_id:id(call.initiatedBy)},participants:call.participants};}

async function finish(call,status,userId,reason,deps={}){
  const CallModel=deps.CallModel||Call,ParticipantModel=deps.ParticipantModel||Participant;
  if(terminal.has(call.status))return safeCall(call,deps);
  assertCallTransition(call.status,status);
  const endedAt=new Date(),supportsAtomic=typeof CallModel.findOneAndUpdate==="function",updated=supportsAtomic?await CallModel.findOneAndUpdate({_id:call._id,status:call.status},{$set:{status,endedAt,endedBy:userId||null,endReason:reason,screenSharingUser:null,acceptingParticipants:false}},{new:true}):null;
  if(supportsAtomic&&!updated){const current=await CallModel.findById(call._id);return current?safeCall(current,deps):null;}
  if(!supportsAtomic){call.status=status;call.endedAt=endedAt;call.endedBy=userId||null;call.endReason=reason;call.screenSharingUser=null;call.acceptingParticipants=false;await call.save();}
  const value=updated||call;
  await ParticipantModel.updateMany({call:value._id,status:{$in:["joined","ringing","invited"]}},{$set:{status:status==="missed"?"missed":"left",leftAt:endedAt,screenSharing:false,handRaised:false,lastConnectionState:"closed"}});
  return safeCall(value,deps);
}

async function markCallMissed(callId,deps={}){
  const CallModel=deps.CallModel||Call,ParticipantModel=deps.ParticipantModel||Participant;
  const call=await CallModel.findOneAndUpdate({_id:callId,status:"ringing"},{$set:{status:"missed",endedAt:new Date(),endedBy:null,endReason:"no_answer",screenSharingUser:null,acceptingParticipants:false}},{new:true});
  if(!call)return null;
  const recipients=await ParticipantModel.find({call:call._id,status:"ringing"});
  await ParticipantModel.updateMany({call:call._id,status:{$in:["joined","ringing","invited"]}},{$set:{status:"missed",leftAt:new Date(),screenSharing:false,handRaised:false,lastConnectionState:"closed"}});
  for(const row of recipients)await createNotification({recipient:row.user,actor:call.initiatedBy,type:"missed_call",title:"Missed CodeHub call",message:"You missed a CodeHub call.",url:"/calls/history",eventKey:`missed-call:${call._id}:${row.user}`}).catch(()=>{});
  return safeCall(call,deps);
}

async function clearStaleParticipant(row,deps={}){
  const ParticipantModel=deps.ParticipantModel||Participant,call=row.call;
  await ParticipantModel.updateOne({_id:row._id,status:row.status},{$set:{status:"left",leftAt:new Date(),screenSharing:false,handRaised:false,lastConnectionState:"closed"}});
  if(id(call.screenSharingUser)===id(row.user))await (deps.CallModel||Call).updateOne({_id:call._id},{$set:{screenSharingUser:null}});
  const remaining=await ParticipantModel.countDocuments({call:call._id,status:"joined",_id:{$ne:row._id}});
  if(!remaining&&call.status==="active")return finish(call,"ended",null,"network_failed",deps);
  return null;
}

async function reconcileUserActiveCall(userId,deps={}){
  const ParticipantModel=deps.ParticipantModel||Participant,now=deps.now instanceof Date?deps.now:new Date(deps.now||Date.now()),isOnline=deps.isOnline||presence.isOnline;
  let query=ParticipantModel.find({user:userId,status:{$in:["invited","ringing","joined"]}});
  if(query.sort)query=query.sort({updatedAt:-1});
  if(query.populate)query=query.populate("call");
  const rows=await query,valid=[];
  for(const row of rows){const call=row.call;if(!call||terminal.has(call.status)){if(row.status!=="left")await ParticipantModel.updateOne({_id:row._id},{$set:{status:call?.status==="missed"?"missed":"left",leftAt:new Date(),lastConnectionState:"closed",screenSharing:false,handRaised:false}});continue;}
    if(call.status==="initiating"&&age(call.startedAt||call.createdAt,now)>INITIATING_TIMEOUT_MS){await finish(call,"failed",null,"server_error",deps);continue;}
    if(call.status==="ringing"&&age(call.startedAt||call.createdAt,now)>RINGING_TIMEOUT_MS){await markCallMissed(call._id,deps);continue;}
    if(call.status==="active"&&row.status==="joined"&&!isOnline(userId)&&age(row.updatedAt||row.joinedAt||call.updatedAt,now)>RECOVERY_TIMEOUT_MS){await clearStaleParticipant(row,deps);continue;}
    const joinable=(call.status==="initiating"&&row.status==="joined")||(call.status==="ringing"&&["joined","ringing"].includes(row.status))||(call.status==="active"&&["joined","invited"].includes(row.status));
    if(joinable)valid.push(row);else await ParticipantModel.updateOne({_id:row._id},{$set:{status:"left",leftAt:new Date(),lastConnectionState:"closed"}});
  }
  valid.sort((a,b)=>new Date(b.call.startedAt||b.call.createdAt)-new Date(a.call.startedAt||a.call.createdAt));
  const selected=valid.shift();
  for(const row of valid){if(row.call.status==="ringing")await markCallMissed(row.call._id,deps);else if(row.call.status==="initiating")await finish(row.call,"failed",null,"server_error",deps);else await clearStaleParticipant(row,deps);}
  return selected?safeCall(selected.call,deps):null;
}

async function reconcileAllActiveCalls(deps={}){const ParticipantModel=deps.ParticipantModel||Participant,userIds=await ParticipantModel.distinct("user",{status:{$in:["invited","ringing","joined"]}}),results=[];for(const userId of userIds)results.push(await reconcileUserActiveCall(userId,deps));return results.filter(Boolean);}
async function isBusy(userId,{excludeCall=null,...deps}={}){const active=await reconcileUserActiveCall(userId,deps);return Boolean(active&&id(active)!==id(excludeCall));}
function withCreationLock(userId,work){const key=id(userId),previous=creationLocks.get(key)||Promise.resolve(),current=previous.catch(()=>{}).then(work);creationLocks.set(key,current);return current.finally(()=>{if(creationLocks.get(key)===current)creationLocks.delete(key);});}

async function createDirectCall(callerId,recipientId,input={},deps={}){return withCreationLock(callerId,async()=>{const access=await permission.assertCanStartDirectCall(callerId,recipientId,{conversationId:input.conversationId,...deps});if(await isBusy(callerId,deps))throw permission.error("CALL_ALREADY_ACTIVE","You have an active call.",409);if(await isBusy(recipientId,deps))throw permission.error("CALL_RECIPIENT_BUSY","The recipient is busy",409);if(!input.allowOffline&&!presence.isOnline(recipientId))throw permission.error("CALL_RECIPIENT_OFFLINE","The recipient is offline",409);const CallModel=deps.CallModel||Call,ParticipantModel=deps.ParticipantModel||Participant,call=await CallModel.create({callType:"direct",mediaMode:input.mediaMode==="video"?"video":"audio",conversation:access.conversation._id,initiatedBy:callerId,status:"ringing",maxParticipants:2});await ParticipantModel.create([{call:call._id,user:callerId,role:"host",status:"joined",joinedAt:new Date(),cameraEnabled:call.mediaMode==="video"},{call:call._id,user:recipientId,role:"participant",status:"ringing",invitedBy:callerId,cameraEnabled:false}]);return safeCall(call,deps);});}

async function createContextualCall(userId,input={},deps={}){return withCreationLock(userId,async()=>{let context,fields={};if(input.callType==="repository"){context=await permission.assertCanStartRepositoryCall(input.repositoryId,userId,deps);fields.repository=context.repository._id;}else if(input.callType==="issue"){context=await permission.assertCanStartIssueCall(input.issueId,userId,deps);fields={repository:context.issue.repository,issue:context.issue._id};}else if(input.callType==="pull_request"){context=await permission.assertCanStartPullRequestCall(input.pullRequestId,userId,deps);fields={repository:context.pullRequest.repository,pullRequest:context.pullRequest._id};}else if(input.callType==="mentor"){if(input.conversationId){context=await permission.assertCanUseMentorConversation(input.conversationId,userId,deps);fields={repository:context.conversation.repository,conversation:context.conversation._id};}else{context=await permission.assertCanStartMentorCall(input.mentorRequestId,userId,deps);fields={repository:context.request.repository,issue:context.request.issue||null,mentorRequest:context.request._id,conversation:context.request.conversation||null};}}else if(input.callType==="guided_contribution"){context=await permission.assertCanStartContributionCall(input.contributionSessionId,userId,deps);fields={repository:context.session.repository,issue:context.session.issue,contributionSession:context.session._id,mentorRequest:context.session.mentorRequest||null};}else throw permission.error("CALL_INVALID_STATE","Invalid contextual call type",400);if(await isBusy(userId,deps))throw permission.error("CALL_ALREADY_ACTIVE","You have an active call.",409);const call=await (deps.CallModel||Call).create({callType:input.callType,mediaMode:input.mediaMode==="video"?"video":"audio",initiatedBy:userId,status:"active",answeredAt:new Date(),maxParticipants:4,...fields});await (deps.ParticipantModel||Participant).create({call:call._id,user:userId,role:context.role==="mentor"?"mentor":"host",status:"joined",joinedAt:new Date(),cameraEnabled:call.mediaMode==="video"});return safeCall(call,deps);});}

async function getCallById(callId,userId,deps={}){const {call}=await permission.assertCanJoinCall(callId,userId,deps);return safeCall(call,deps);}
async function acceptCall(callId,userId,input={},deps={}){const {call,participant}=await permission.assertParticipant(callId,userId,deps);if(call.status==="active"&&participant.status==="joined")return safeCall(call,deps);if(call.status!=="ringing"||participant.status!=="ringing")throw permission.error("CALL_INVALID_STATE","This call cannot be accepted",409);if(await isBusy(userId,{...deps,excludeCall:callId})){await finish(call,"rejected",userId,"busy",deps);throw permission.error("CALL_RECIPIENT_BUSY","Leave your current call before accepting",409);}assertCallTransition(call.status,"active");call.status="active";call.answeredAt=new Date();await call.save();participant.status="joined";participant.joinedAt=new Date();participant.microphoneEnabled=input.microphoneEnabled!==false;participant.cameraEnabled=call.mediaMode==="video"&&input.cameraEnabled!==false;participant.lastConnectionState="connecting";await participant.save();return safeCall(call,deps);}
async function rejectCall(callId,userId,deps={}){const {call,participant}=await permission.assertParticipant(callId,userId,deps);if(terminal.has(call.status))return safeCall(call,deps);if(call.status!=="ringing"||participant.status!=="ringing")throw permission.error("CALL_INVALID_STATE","This call cannot be rejected",409);participant.status="rejected";participant.leftAt=new Date();await participant.save();return finish(call,"rejected",userId,"rejected",deps);}
async function cancelCall(callId,userId,deps={}){const {call,participant}=await permission.assertParticipant(callId,userId,deps);if(terminal.has(call.status))return safeCall(call,deps);if(id(call.initiatedBy)!==id(userId)||call.status!=="ringing")throw permission.error("CALL_INVALID_STATE","Only the caller can cancel a ringing call",409);participant.status="left";participant.leftAt=new Date();await participant.save();return finish(call,"cancelled",userId,"cancelled",deps);}
async function endCall(callId,userId,reason="participant_ended",deps={}){const {call}=await permission.assertParticipant(callId,userId,deps);if(terminal.has(call.status))return safeCall(call,deps);if(call.status!=="active")throw permission.error("CALL_NOT_ACTIVE","This call is not active",409);return finish(call,"ended",userId,id(call.initiatedBy)===id(userId)?"caller_ended":reason,deps);}
async function joinCall(callId,userId,input={},deps={}){const reconciled=await reconcileUserActiveCall(userId,deps);if(reconciled&&id(reconciled)!==id(callId))throw permission.error("CALL_RECIPIENT_BUSY","Leave your current call before joining",409);const value=await permission.assertCanJoinCall(callId,userId,deps),ParticipantModel=deps.ParticipantModel||Participant,existing=value.participant||await ParticipantModel.findOne({call:value.call._id,user:userId});if(existing?.status==="joined"){existing.lastConnectionState="connecting";existing.leftAt=null;await existing.save();return safeCall(value.call,deps);}const joined=await ParticipantModel.countDocuments({call:value.call._id,status:"joined",user:{$ne:userId}});if(joined>=value.call.maxParticipants)throw permission.error("CALL_PARTICIPANT_LIMIT","This call has reached the current participant limit",409);let participant=existing;if(!participant)participant=await ParticipantModel.create({call:value.call._id,user:userId,role:value.role||"participant",status:"joined",joinedAt:new Date(),lastConnectionState:"connecting"});else{participant.status="joined";participant.joinedAt=participant.joinedAt||new Date();participant.leftAt=null;participant.lastConnectionState="connecting";participant.microphoneEnabled=input.microphoneEnabled!==false;participant.cameraEnabled=value.call.mediaMode==="video"&&input.cameraEnabled!==false;await participant.save();}return safeCall(value.call,deps);}
async function leaveCall(callId,userId,deps={}){const {call,participant}=await permission.assertParticipant(callId,userId,deps);if(participant.status==="left"||participant.status==="removed"||participant.status==="missed")return safeCall(call,deps);participant.status="left";participant.leftAt=new Date();participant.screenSharing=false;participant.handRaised=false;participant.lastConnectionState="closed";await participant.save();if(id(call.screenSharingUser)===id(userId)){call.screenSharingUser=null;await call.save();}const remaining=await (deps.ParticipantModel||Participant).countDocuments({call:call._id,status:"joined"});if(!remaining&&call.status==="active")return finish(call,"ended",userId,"participant_ended",deps);return safeCall(call,deps);}
async function resolveCallInvitee(identifier,{UserModel=User}={}){const value=String(identifier?._id||identifier?.id||identifier||"").trim();if(!value)throw permission.error("CALL_MEMBER_NOT_FOUND","Repository member not found",404);const objectId=/^[a-f\d]{24}$/i.test(value),user=objectId?await UserModel.findById(value):await UserModel.findOne({username:value});if(!user)throw permission.error("CALL_MEMBER_NOT_FOUND","Repository member not found",404);return id(user);}
async function inviteParticipant(callId,inviterId,invitee,deps={}){const invitedUserId=await resolveCallInvitee(invitee,deps),{call}=await permission.assertCanInviteParticipant(callId,inviterId,invitedUserId,deps),ParticipantModel=deps.ParticipantModel||Participant,existing=await ParticipantModel.findOne({call:call._id,user:invitedUserId});if(existing?.status==="joined")throw permission.error("CALL_ALREADY_PARTICIPANT","This user is already in the call",409);if(["invited","ringing"].includes(existing?.status))throw permission.error("CALL_INVITATION_ALREADY_PENDING","This user already has a pending invitation.",409);const count=await ParticipantModel.countDocuments({call:call._id,status:{$in:["invited","ringing","joined"]}});if(count>=call.maxParticipants)throw permission.error("CALL_PARTICIPANT_LIMIT","This call has reached the four-participant limit",409);const invitationExpiresAt=new Date(Date.now()+CALL_INVITATION_TTL_MS);let participant;try{if(existing){existing.status="invited";existing.invitedBy=inviterId;existing.invitationExpiresAt=invitationExpiresAt;existing.leftAt=null;participant=await existing.save();}else participant=await ParticipantModel.create({call:call._id,user:invitedUserId,invitedBy:inviterId,invitationExpiresAt,status:"invited"});}catch(error){if(error.code===11000){const duplicate=await ParticipantModel.findOne({call:call._id,user:invitedUserId});throw permission.error(duplicate?.status==="joined"?"CALL_ALREADY_PARTICIPANT":"CALL_INVITATION_ALREADY_PENDING",duplicate?.status==="joined"?"This user is already in the call":"This user already has a pending invitation.",409);}throw error;}await(deps.createNotification||createNotification)({recipient:invitedUserId,actor:inviterId,repository:call.repository,type:"call_invitation",title:"CodeHub call invitation",message:"You were invited to a CodeHub call.",url:`/calls/${call._id}`,eventKey:`call-invite:${call._id}:${invitedUserId}`}).catch(()=>{});return participant;}
async function declineInvitation(callId,userId,deps={}){const {call,participant}=await permission.assertParticipant(callId,userId,deps);if(call.status!=="active")throw permission.error("CALL_NOT_ACTIVE","This call is no longer active",409);if(participant.status==="rejected")return safeCall(call,deps);if(!["invited","ringing"].includes(participant.status))throw permission.error("CALL_INVALID_STATE","This invitation cannot be declined",409);participant.status="rejected";participant.leftAt=new Date();participant.lastConnectionState="closed";await participant.save();return safeCall(call,deps);}
async function removeParticipant(callId,hostId,userId,deps={}){const host=await permission.assertParticipant(callId,hostId,deps);if(host.participant.role!=="host")throw permission.error("CALL_FORBIDDEN","Only the host may remove participants");if(id(userId)===id(hostId))throw permission.error("CALL_INVALID_STATE","Use Leave call instead",400);const participant=await (deps.ParticipantModel||Participant).findOne({call:callId,user:userId});if(!participant)throw permission.error("CALL_NOT_FOUND","Participant not found",404);if(participant.status==="removed")return participant;participant.status="removed";participant.leftAt=new Date();participant.screenSharing=false;participant.handRaised=false;participant.lastConnectionState="closed";await participant.save();if(id(host.call.screenSharingUser)===id(userId)){host.call.screenSharingUser=null;await host.call.save();}return participant;}
async function updateParticipant(callId,userId,patch,deps={}){const {call,participant}=await permission.assertParticipant(callId,userId,deps);if(call.status!=="active"||participant.status!=="joined")throw permission.error("CALL_NOT_ACTIVE","This call is not active",409);for(const key of["microphoneEnabled","cameraEnabled","handRaised","lastConnectionState"])if(patch[key]!==undefined)participant[key]=patch[key];if(patch.handRaised===true)participant.handRaisedAt=new Date();if(patch.handRaised===false)participant.handRaisedAt=null;await participant.save();return participant;}
async function setScreenShare(callId,userId,active,deps={}){const {call,participant}=await permission.assertCanShareScreen(callId,userId,deps);if(active){call.screenSharingUser=userId;participant.screenSharing=true;}else if(id(call.screenSharingUser)===id(userId)){call.screenSharingUser=null;participant.screenSharing=false;}await Promise.all([call.save(),participant.save()]);return{call,participant};}
async function getActiveCallForUser(userId,deps={}){return reconcileUserActiveCall(userId,deps);}
async function getCallHistory(userId,deps={}){const ParticipantModel=deps.ParticipantModel||Participant,rows=await ParticipantModel.find({user:userId}).sort({createdAt:-1}).limit(100).populate({path:"call",populate:{path:"initiatedBy",select:"_id username name avatarUrl"}}).lean();return rows.filter(row=>row.call).map(row=>({...row.call,currentParticipant:{role:row.role,status:row.status}}));}

module.exports={terminal,transitions,INITIATING_TIMEOUT_MS,RINGING_TIMEOUT_MS,RECOVERY_TIMEOUT_MS,CALL_INVITATION_TTL_MS,creationLocks,assertCallTransition,isBusy,safeCall,reconcileUserActiveCall,reconcileAllActiveCalls,createDirectCall,createContextualCall,getCallById,acceptCall,rejectCall,cancelCall,endCall,joinCall,leaveCall,resolveCallInvitee,listEligibleInvitees,invitationPayload,inviteParticipant,declineInvitation,removeParticipant,updateParticipant,setScreenShare,markCallMissed,getActiveCallForUser,getCallHistory,finish};
