const Conversation=require("../models/conversationModel"),Member=require("../models/conversationMemberModel"),Block=require("../models/chatBlockModel"),Message=require("../models/chatMessageModel"),Issue=require("../models/issueModel"),PullRequest=require("../models/pullRequestModel");
const {resolveRepositoryPermissionContext}=require("./repositoryPermissionService");
const id=v=>String(v?._id||v?.id||v||""); const error=(code,message,status=403)=>Object.assign(new Error(message),{code,status});
async function loadConversation(value,{ConversationModel=Conversation}={}){const conversation=typeof value==="object"&&value?.type?value:await ConversationModel.findById(value);if(!conversation||conversation.isArchived)throw error("CONVERSATION_NOT_FOUND","Conversation not found",404);return conversation;}
async function repositoryContext(conversation,{IssueModel=Issue,PullModel=PullRequest}={}){if(conversation.repository)return id(conversation.repository);if(conversation.issue){const issue=await IssueModel.findById(conversation.issue).select("repository").lean();if(!issue)throw error("ISSUE_NOT_FOUND","Issue not found",404);return id(issue.repository);}if(conversation.pullRequest){const pull=await PullModel.findById(conversation.pullRequest).select("repository").lean();if(!pull)throw error("PULL_REQUEST_NOT_FOUND","Pull request not found",404);return id(pull.repository);}return "";}
async function getConversationAccess(value,userId,deps={}){const conversation=await loadConversation(value,deps);const user=id(userId);if(!user)throw error("AUTHENTICATION_REQUIRED","Authentication required",401);
 if(["direct","mentor"].includes(conversation.type)){const membership=await (deps.MemberModel||Member).findOne({conversation:conversation._id,user}).lean();return{conversation,canView:Boolean(membership),canSend:Boolean(membership&&conversation.mentorStatus!=="closed"),membership,repositoryContext:null};}
 const repositoryId=await repositoryContext(conversation,deps);const context=await resolveRepositoryPermissionContext(repositoryId,user,{skipExpirationWrite:true,...deps.repositoryDependencies});const canView=context.repository.visibility!=="private"||Boolean(context.role);const active=Boolean(context.role)&&!["expired","not_started","suspended"].includes(context.status)&&conversation.isArchived!==true;return{conversation,canView,canSend:active,membership:null,repositoryContext:context};}
async function assertCanViewConversation(value,userId,deps){const access=await getConversationAccess(value,userId,deps);if(!access.canView)throw error("FORBIDDEN","You do not have access to this conversation");return access;}
async function assertCanSendMessage(value,userId,deps={}){const access=await assertCanViewConversation(value,userId,deps);if(!access.canSend){const code=access.repositoryContext?.status==="expired"?"TEMPORARY_ACCESS_EXPIRED":"REPOSITORY_ACCESS_REVOKED";throw error(code,"You cannot send messages to this conversation");}if(access.conversation.type==="direct"){const others=await (deps.MemberModel||Member).find({conversation:access.conversation._id,user:{$ne:userId}}).select("user").lean();const other=others[0]?.user;if(other&&await (deps.BlockModel||Block).exists({$or:[{blocker:userId,blocked:other},{blocker:other,blocked:userId}]}))throw error("USER_BLOCKED","Direct messages are blocked");}return access;}
async function assertOwnMessage(messageId,userId,deps={}){const message=await (deps.MessageModel||Message).findById(messageId);if(!message)throw error("MESSAGE_NOT_FOUND","Message not found",404);await assertCanViewConversation(message.conversation,userId,deps);if(id(message.sender)!==id(userId))throw error("FORBIDDEN","You may only modify your own messages");return message;}
async function assertCanCreateDirectConversation(a,b,{BlockModel=Block}={}){if(id(a)===id(b))throw error("CANNOT_MESSAGE_SELF","You cannot message yourself",400);if(await BlockModel.exists({$or:[{blocker:a,blocked:b},{blocker:b,blocked:a}]}))throw error("USER_BLOCKED","Direct messages are blocked");return true;}
module.exports={error,getConversationAccess,assertCanViewConversation,assertCanSendMessage,assertOwnMessage,assertCanCreateDirectConversation,repositoryContext};
