const { HEALTH_SCORE_VERSION, HEALTH_WEIGHTS, HEALTH_RANGES, HEALTH_LEVELS } = require("../constants/repositoryHealth");
const cache=new Map(); const CACHE_TTL_MS=300000;
const pathsOf=(v=[])=>v.map(x=>String(x.path||x.filename||x).replace(/\\/g,"/").toLowerCase());
const has=(p,r)=>p.some(x=>r.test(x)); const clamp=(n,max)=>Math.min(max,Math.max(0,Number.isFinite(n)?n:0));
const check=(label,points,max,evidence,recommendation)=>({label,points:clamp(points,max),max,status:points>=max?"pass":points>0?"partial":"not_configured",evidence,recommendation:points<max?recommendation:null});
const group=(label,max,details)=>({label,score:clamp(details.reduce((n,x)=>n+x.points,0),max),max,details});
const kind=(r,k)=>new RegExp(k,"i").test(`${r.workflowType||""} ${r.workflowName||r.name||""} ${r.workflowPath||r.path||""}`);
const latest=(runs,k)=>runs.filter(r=>kind(r,k)).sort((a,b)=>new Date(b.completedAt||b.createdAt||0)-new Date(a.completedAt||a.createdAt||0))[0];
const passed=r=>r?.status==="success"&&Boolean(r.completedAt); const age=(d,now)=>d?(now-new Date(d))/86400000:Infinity;
function calculateRepositoryHealth(e,{range="30d",now=new Date()}={}){
 if(!HEALTH_RANGES[range]) throw Object.assign(new Error("Range must be 30d, 90d, or 180d"),{status:400});
 const p=pathsOf(e.files), readme=e.readme||"", pkg=e.packageJson||{}, runs=e.workflowRuns||[], workflows=e.workflows||[], commits=e.commits||[], issues=e.issues||[], pulls=e.pullRequests||[], releases=e.releases||[];
 const setup=/installation|install|setup|getting started|prerequisites|usage|run locally/i.test(readme), contributing=has(p,/(^|\/)contributing(\.|$)/), license=has(p,/(^|\/)(license|copying)(\.|$)/), extraDocs=has(p,/(^|\/)docs\//)||has(p,/(^|\/)(changelog|security|code_of_conduct)(\.|$)/);
 const testRun=latest(runs,"test"), lintRun=latest(runs,"lint"), buildRun=latest(runs,"build"), securityRun=latest(runs,"security|audit"), staticRun=latest(runs,"static|quality"), deployRun=latest(runs,"deployment|deploy");
 const configured=k=>workflows.some(w=>kind(w,k)); const lastCommit=commits.map(c=>new Date(c.time)).filter(d=>!Number.isNaN(+d)).sort((a,b)=>b-a)[0]; const lastAge=age(lastCommit,now);
 const recentPoints=lastAge<=7?4:lastAge<=30?3:lastAge<=90?2:lastAge<=180?1:0; const weeks=Math.min(3,new Set(commits.filter(c=>age(c.time,now)<=HEALTH_RANGES[range]).map(c=>{const d=new Date(c.time);return `${d.getUTCFullYear()}-${Math.floor((d-Date.UTC(d.getUTCFullYear(),0,1))/604800000)}`;})).size);
 const meaningful=[...issues,...pulls,...releases].some(x=>age(x.updatedAt||x.mergedAt||x.publishedAt||x.createdAt,now)<=HEALTH_RANGES[range]); const open=issues.filter(i=>!(i.status==="closed"||i.closed||i.state==="closed")), high=open.filter(i=>["high","critical"].includes(i.priority)), stale=open.filter(i=>age(i.updatedAt||i.createdAt,now)>30), staleRatio=open.length?stale.length/open.length:0;
 const sensitive= p.filter(x=>/(^|\/)(\.env($|\.)|id_rsa|.*\.pem$|credentials?\.json$|secrets?\.)/.test(x)); const protectedBranch=(e.branchProtections||[]).some(x=>x.enabled!==false&&(x.requirePullRequest||x.blockDirectCommits)); const warnings=(e.fileWarnings||[]).length;
 const structured=has(p,/(^|\/)(src|components|controllers|routes|models|services|tests)\//), issueTemplate=has(p,/(^|\/)\.github\/issue_template\//), conduct=has(p,/(^|\/)code_of_conduct(\.|$)/), devCommands=/npm |pnpm |yarn |pytest|mvn |gradle |run locally/i.test(readme), starter=issues.some(i=>(i.labels||[]).some(l=>/good first issue|beginner-friendly|first contribution|help wanted|easy|starter/i.test(l.name||l)));
 const categories={
  documentation:group("Documentation",15,[check("README",has(p,/(^|\/)readme(\.|$)/)?4:0,4,"Repository file metadata","Add a README"),check("Repository description",e.description?2:0,2,e.description?"Description present":"Not configured","Add a repository description"),check("Setup guidance",setup?3:0,3,setup?"Setup instructions found":"Not configured","Document installation and setup"),check("Contributing guide",contributing?2:0,2,"Repository file metadata","Add CONTRIBUTING.md"),check("License",license?2:0,2,"Repository file metadata","Add a license"),check("Additional documentation",extraDocs?2:0,2,"Repository file metadata","Add project documentation")]),
  automatedTests:group("Automated tests",20,[check("Test files",has(p,/(^|\/)(__tests__|tests?)(\/|\.)|\.(test|spec)\.(js|jsx|ts|tsx)$/)?5:0,5,"Repository file metadata","Add automated tests"),check("Test script",pkg.scripts?.test&&!/no test specified/i.test(pkg.scripts.test)?4:0,4,pkg.scripts?.test?"Test script found":"Not configured","Configure a test script"),check("Test workflow",configured("test")?3:0,3,configured("test")?"Workflow configured":"Not configured","Configure a test workflow"),check("Latest test result",passed(testRun)?5:0,5,testRun?`Latest stored result: ${testRun.status}`:"Test execution result unavailable","Pass the test workflow"),check("Recent test execution",testRun&&age(testRun.completedAt,now)<=HEALTH_RANGES[range]?3:0,3,testRun?"Stored workflow timestamp":"Not configured","Run tests in the selected range")]),
  maintenance:group("Maintenance activity",10,[check("Recent commits",recentPoints,4,lastCommit?lastCommit.toISOString():"No commits","Commit project improvements"),check("Activity across weeks",weeks,3,`${weeks} active weeks`,"Maintain activity across multiple weeks"),check("Meaningful recent activity",meaningful?2:0,2,meaningful?"Recent issue, pull request, or release activity":"No recent activity","Record meaningful project activity"),check("Meaningful commit",commits.length?1:0,1,`${commits.length} commits`,"Create the first meaningful commit")]),
  issueManagement:group("Issue management",10,[check("No unresolved high-priority issues",issues.length&&!high.length?3:0,3,issues.length?`${high.length} unresolved high-priority issues`:"Not configured","Resolve high-priority issues"),check("Low stale-issue ratio",issues.length?(staleRatio<=.25?3:staleRatio<=.5?1:0):0,3,issues.length?`${stale.length} stale open issues`:"Not configured","Review stale issues"),check("Labels or priorities",issues.some(i=>(i.labels||[]).length||i.priority&&i.priority!=="none")?2:0,2,"Stored issue metadata","Use labels or priorities"),check("Recently resolved issues",issues.some(i=>(i.status==="closed"||i.closed)&&age(i.closedAt||i.updatedAt,now)<=HEALTH_RANGES[range])?2:0,2,"Stored issue resolution timestamps","Resolve tracked issues")]),
  security:group("Security",15,[check("No exposed-secret warning",sensitive.length?0:5,5,sensitive.length?"Protected filename warnings detected":"No protected filename warnings","Remove sensitive files and rotate credentials"),check("Dependency security check",passed(securityRun)?4:0,4,securityRun?`Latest stored result: ${securityRun.status}`:"Dependency security scan not configured","Add a safe security workflow"),check("Default branch protection",protectedBranch?2:0,2,protectedBranch?"Protection enabled":"Not configured","Protect the default branch"),check("Exactly one owner",e.ownerDuplicate?0:1,1,e.ownerDuplicate?"Owner anomaly detected":"Exactly one effective owner","Normalize repository ownership"),check("Expired write access",e.expiredWriteAccess?0:1,1,e.expiredWriteAccess?"Expired write access detected":"No expired write access detected","Remove expired write access"),check("Private access validation",e.visibility==="private"&&!e.ownerDuplicate?2:0,2,e.visibility==="private"?"Stored authorization invariant":"Not applicable or unhealthy","Validate private repository access")]),
  codeQuality:group("Code quality",15,[check("Lint configuration",pkg.scripts?.lint||has(p,/(^|\/)(eslint|prettier|biome)(\.config|rc|$)/)?3:0,3,"Stored configuration metadata","Configure linting"),check("Latest lint result",passed(lintRun)?4:0,4,lintRun?`Latest stored result: ${lintRun.status}`:"Not configured","Pass linting in automation"),check("Successful build",passed(buildRun)?3:0,3,buildRun?`Latest stored result: ${buildRun.status}`:"Not configured","Complete a successful build"),check("Structured source layout",structured?2:0,2,"Repository paths","Organize source directories"),check("No duplicate or oversized warnings",warnings?0:1,1,warnings?`${warnings} file warnings`:"No stored file warnings","Resolve duplicate or oversized files"),check("Static analysis",passed(staticRun)?2:0,2,staticRun?`Latest stored result: ${staticRun.status}`:"Not configured","Configure static analysis")]),
  buildDeployment:group("Build and deployment",5,[check("Build workflow",configured("build")?1:0,1,configured("build")?"Configured":"Not configured","Configure a build workflow"),check("Latest build",passed(buildRun)?2:0,2,buildRun?`Latest stored result: ${buildRun.status}`:"Not configured","Pass the build workflow"),check("Deployment workflow",configured("deployment|deploy")?1:0,1,configured("deployment|deploy")?"Configured":"Deployment not configured","Configure deployment automation"),check("Latest deployment",passed(deployRun)?1:0,1,deployRun?`Latest stored result: ${deployRun.status}`:"Deployment not configured","Complete a successful deployment")]),
  beginnerFriendliness:group("Beginner friendliness",10,[check("Contributing guide",contributing?2:0,2,"Repository paths","Add CONTRIBUTING.md"),check("Setup guidance",setup?2:0,2,"README evidence","Document setup"),check("Beginner issues",starter?2:0,2,"Stored issue labels","Label beginner-friendly issues"),check("Issue templates",issueTemplate?1:0,1,"Repository paths","Add issue templates"),check("Code of conduct",conduct?1:0,1,"Repository paths","Add a code of conduct"),check("Development commands",devCommands?1:0,1,"README evidence","Document development commands"),check("Repository description",e.description?1:0,1,e.description?"Description present":"Not configured","Add a repository description")])};
 const raw=Object.values(categories).reduce((n,c)=>n+c.score,0), score=clamp(raw,100), published=releases.filter(r=>!r.draft&&r.publishedAt), ageDays=Math.max(0,age(e.createdAt,now)); const insufficientData=commits.length<3&&!pulls.length&&!issues.length&&!runs.some(r=>r.completedAt)&&!published.length&&ageDays<7;
 const recommendations=Object.values(categories).flatMap(c=>c.details).filter(d=>d.recommendation).sort((a,b)=>(b.max-b.points)-(a.max-a.points)).slice(0,5).map(d=>d.recommendation); const status=insufficientData?"insufficient_data":HEALTH_LEVELS.find(x=>score>=x.min).status;
 return {score,status,insufficientData,version:HEALTH_SCORE_VERSION,range,categories,recommendations,calculatedAt:now};
}
const key=(id,r)=>`${id}:${r}:${HEALTH_SCORE_VERSION}`; function getCachedHealth(id,r,now=Date.now()){const x=cache.get(key(id,r));if(!x||x.expiresAt<=now){cache.delete(key(id,r));return null;}return x.value;} function setCachedHealth(id,r,value,now=Date.now()){cache.set(key(id,r),{value,expiresAt:now+CACHE_TTL_MS});return value;} function invalidateRepositoryHealthCache(id){const p=`${id}:`;for(const k of cache.keys())if(k.startsWith(p))cache.delete(k);}
module.exports={calculateRepositoryHealth,getCachedHealth,setCachedHealth,invalidateRepositoryHealthCache,CACHE_TTL_MS};
