const crypto=require("crypto"),path=require("path"),Message=require("../models/chatMessageModel"),Conversation=require("../models/conversationModel"),permission=require("./chatPermissionService"),chat=require("./chatService"),{s3,S3_BUCKET}=require("../config/aws-config"),{LIMITS}=require("../constants/chatConstants");
const TYPES=new Map([[".webm",["audio/webm","audio/webm;codecs=opus"]],[".ogg",["audio/ogg"]],[".mp4",["audio/mp4"]],[".mp3",["audio/mpeg"]]]);
const id=v=>String(v?._id||v?.id||v||"");
const safeName=value=>path.basename(String(value||"voice-message.webm")).replace(/[\u0000-\u001f\u007f]/g,"").slice(0,255);
function signatureMatches(buffer,ext){if(ext===".webm")return buffer.subarray(0,4).equals(Buffer.from([0x1a,0x45,0xdf,0xa3]));if(ext===".ogg")return buffer.subarray(0,4).toString()==="OggS";if(ext===".mp4")return buffer.subarray(4,8).toString()==="ftyp";if(ext===".mp3")return buffer.subarray(0,3).toString()==="ID3"||(buffer[0]===0xff&&(buffer[1]&0xe0)===0xe0);return false;}
function validateVoice(file,durationMs){if(!file?.buffer?.length)throw permission.error("VOICE_FORMAT_NOT_ALLOWED","Voice message is empty",400);if(file.size>LIMITS.voiceBytes)throw permission.error("VOICE_MESSAGE_TOO_LARGE","Voice message exceeds 10 MB",413);const originalName=safeName(file.originalname),ext=path.extname(originalName).toLowerCase(),mime=String(file.mimetype||"").toLowerCase(),allowed=TYPES.get(ext);if(!allowed||!allowed.includes(mime)||!signatureMatches(file.buffer,ext))throw permission.error("VOICE_FORMAT_NOT_ALLOWED","Voice-message format is not allowed",400);const duration=Number(durationMs);if(!Number.isFinite(duration)||duration<=0)throw permission.error("VOICE_FORMAT_NOT_ALLOWED","A valid voice-message duration is required",400);if(duration>LIMITS.voiceDurationMs)throw permission.error("VOICE_MESSAGE_TOO_LONG","Voice message exceeds five minutes",413);return{originalName,mimeType:mime,durationMs:Math.round(duration)};}
function waveform(value){let rows=value;if(typeof rows==="string"){try{rows=JSON.parse(rows);}catch{rows=[];}}return(Array.isArray(rows)?rows:[]).slice(0,100).map(item=>Math.max(0,Math.min(1,Number(item)||0)));}
async function create(conversationId,userId,file,input={},deps={}){await permission.assertCanSendMessage(conversationId,userId,deps);const MessageModel=deps.MessageModel||Message,ConversationModel=deps.ConversationModel||Conversation,storage=deps.storage||s3,bucket=deps.bucket||S3_BUCKET,clientMessageId=chat.clean(input.clientMessageId,120);if(!clientMessageId)throw permission.error("INVALID_MESSAGE","clientMessageId is required",400);const duplicate=await MessageModel.findOne({conversation:conversationId,sender:userId,clientMessageId}).populate?.("sender","_id username name avatarUrl lastSeenAt");if(duplicate)return chat.safeMessage(duplicate);const meta=validateVoice(file,input.durationMs),storageKey=`chat/voice/${userId}/${crypto.randomUUID()}`,checksum=crypto.createHash("sha256").update(file.buffer).digest("hex");await storage.putObject({Bucket:bucket,Key:storageKey,Body:file.buffer,ContentType:meta.mimeType,ServerSideEncryption:"AES256"}).promise();let saved;try{const conversation=await ConversationModel.findOneAndUpdate({_id:conversationId,isArchived:false},{$inc:{lastSequence:1}},{new:true});if(!conversation)throw permission.error("CONVERSATION_NOT_FOUND","Conversation not found",404);saved=await MessageModel.create({conversation:conversationId,sender:userId,sequence:conversation.lastSequence,clientMessageId,messageType:"voice",content:"",replyTo:input.replyTo||null,voice:{storageKey,...meta,sizeBytes:file.size,waveform:waveform(input.waveform),checksum}});await ConversationModel.updateOne({_id:conversationId},{$set:{lastMessage:saved._id,lastMessageAt:saved.createdAt}});await chat.notify(conversation,saved,userId,deps);return chat.safeMessage(saved);}catch(error){await storage.deleteObject({Bucket:bucket,Key:storageKey}).promise().catch(()=>{});throw error;}}
async function load(messageId,userId,{MessageModel=Message,storage=s3,bucket=S3_BUCKET,...deps}={}){const message=await MessageModel.findById(messageId).select("+voice.storageKey");if(!message||message.messageType!=="voice"||message.deletedAt||message.moderationStatus==="hidden")throw permission.error("VOICE_MESSAGE_NOT_FOUND","Voice message not found",404);await permission.assertCanViewConversation(message.conversation,userId,deps);const object=await storage.getObject({Bucket:bucket,Key:message.voice.storageKey}).promise();return{message,body:object.Body};}
async function remove(messageId,userId,{MessageModel=Message,storage=s3,bucket=S3_BUCKET,...deps}={}){const message=await permission.assertOwnMessage(messageId,userId,{MessageModel,...deps});if(message.messageType!=="voice")throw permission.error("VOICE_MESSAGE_NOT_FOUND","Voice message not found",404);if(message.deletedAt)return chat.safeMessage(message);const stored=await MessageModel.findById(messageId).select("+voice.storageKey");message.deletedAt=new Date();message.deletedBy=userId;await message.save();if(stored?.voice?.storageKey)await storage.deleteObject({Bucket:bucket,Key:stored.voice.storageKey}).promise().catch(()=>{});return chat.safeMessage(message);}
module.exports={TYPES,safeName,signatureMatches,validateVoice,waveform,create,load,remove};
